;;;; Pruebas del dibujo AutoLISP (engine.lisp, sección AUTOLISP), sin la app.
;;;; sbcl --script tests/autolisp/test_autolisp.lisp   → imprime "N/N OK" o los fallos.
(load (merge-pathnames "../../engine.lisp" *load-truename*))
(setf *read-default-float-format* 'double-float)
(defvar *ok* 0) (defvar *mal* 0)
(defun cerca (a b &optional (tol 1d-9))
  (cond ((and (numberp a) (numberp b)) (<= (abs (- a b)) (* tol (max 1 (abs a) (abs b)))))
        ((and (consp a) (consp b)) (and (cerca (car a) (car b) tol) (cerca (cdr a) (cdr b) tol)))
        (t (equalp a b))))
(defmacro prueba (nombre forma esperado)
  `(let ((v (handler-case ,forma (error (c) (list :error (format nil "~a" c))))))
     (if (cerca v ,esperado) (incf *ok*)
         (progn (incf *mal*) (format t "MAL ~a: ~s  (esperado ~s)~%" ,nombre v ,esperado)))))
(defun sin-1 (l) (remove -1 l :key #'car))   ; la lista sin el ename (que no se compara)

(hk-al-nuevo)
;; entmake / entmakex / entget
(prueba "entmake devuelve la lista" (entmake '((0 . "LINE") (10 0 0) (11 3 4))) '((0 . "LINE") (10 0 0) (11 3 4)))
(prueba "entget: punto 3D, capa 0, handle"
        (sin-1 (entget (entlast))) '((0 . "LINE") (5 . "1F0") (8 . "0") (10 0d0 0d0 0d0) (11 3d0 4d0 0d0)))
(prueba "entmake sin dato obligatorio → nil" (entmake '((0 . "CIRCLE") (10 0 0))) nil)
(prueba "tipo desconocido → nil" (entmake '((0 . "RAYO") (10 0 0))) nil)
(prueba "el código 100 se ignora" (null (entmake '((0 . "CIRCLE") (100 . "AcDbEntity") (8 . "C") (10 1 1) (40 . 2)))) nil)
(prueba "la capa se crea sola" (cdr (assoc 2 (tblsearch "LAYER" "C"))) "C")
(prueba "entmakex → ename" (hk-ename-p (entmakex '((0 . "POINT") (10 5 5)))) t)
(prueba "LWPOLYLINE: 90 contado, vértices 2D"
        (let ((d (entget (entmakex '((0 . "LWPOLYLINE") (70 . 1) (10 0 0) (10 2 0) (10 2 1))))))
          (list (cdr (assoc 90 d)) (cdr (assoc 10 d))))
        '(3 (0d0 0d0)))
(prueba "ARC: ángulos en radianes"
        (cdr (assoc 51 (entget (entmakex (list '(0 . "ARC") '(10 0 0) '(40 . 1) '(50 . 0) (cons 51 (/ pi 2))))))) (/ pi 2))
(prueba "DIMENSION alineada: 42 = medida" (cdr (assoc 42 (entget (entmakex '((0 . "DIMENSION") (13 0 0) (14 3 4) (10 3 5)))))) 5d0)
(prueba "DIMENSION girada 0: proyección en x" (cdr (assoc 42 (entget (entmakex '((0 . "DIMENSION") (70 . 32) (50 . 0) (13 0 0) (14 3 4)))))) 3d0)
;; ssget / sslength / ssname
(prueba "ssget _X por tipo" (sslength (ssget "_X" '((0 . "LINE")))) 1)
(prueba "ssget X sin filtro" (sslength (ssget "X")) 7)
(prueba "ssget por capa" (sslength (ssget "_X" '((8 . "C")))) 1)
(prueba "ssget comodín y comas" (sslength (ssget "_X" '((0 . "LINE,CIRC*")))) 2)
(prueba "ssget <OR" (sslength (ssget "_X" '((-4 . "<OR") (0 . "ARC") (0 . "POINT") (-4 . "OR>")))) 2)
(prueba "ssget relacional" (sslength (ssget "_X" '((0 . "CIRCLE") (-4 . ">=") (40 . 2)))) 1)
(prueba "ssget color PORCAPA = 256" (sslength (ssget "_X" '((62 . 256)))) 7)
(prueba "ssget sin nada → nil" (ssget "_X" '((0 . "HATCH"))) nil)
(prueba "sslength de nil es error (como AutoCAD)" (car (handler-case (sslength nil) (error () '(:error)))) :error)
(prueba "ssname fuera de rango → nil" (ssname (ssget "_X" '((0 . "LINE"))) 5) nil)
(prueba "ssget de pantalla → nil" (ssget) nil)
;; entmod / entdel / entnext
(let* ((e (ssname (ssget "_X" '((0 . "LINE"))) 0)) (d (entget e)))
  (prueba "entmod cambia el punto" (progn (entmod (subst '(11 6.0 8.0 0.0) (assoc 11 d) d)) (cdr (assoc 11 (entget e)))) '(6d0 8d0 0d0))
  (prueba "entmod no cambia el tipo" (entmod (subst '(0 . "CIRCLE") (assoc 0 d) d)) nil)
  (prueba "entdel borra" (progn (entdel e) (list (entget e) (ssget "_X" '((0 . "LINE"))))) '(nil nil))
  (prueba "entdel otra vez recupera" (progn (entdel e) (sslength (ssget "_X" '((0 . "LINE"))))) 1))
(prueba "entnext: primera entidad" (cdr (assoc 0 (entget (entnext)))) "LINE")
;; wcmatch
(prueba "wcmatch *" (wcmatch "LINEA" "LIN*") t)
(prueba "wcmatch ~" (wcmatch "LINE" "~LINE") nil)
(prueba "wcmatch # y @" (wcmatch "A1" "@#") t)
(prueba "wcmatch [ ]" (wcmatch "B" "[A-C]") t)
(prueba "wcmatch distingue mayúsculas" (wcmatch "line" "LINE") nil)
;; utilidades
(prueba "strcat/itoa" (strcat "Hay " (itoa 3) " lineas") "Hay 3 lineas")
(prueba "itoa de real es error" (car (handler-case (itoa 1.5) (error () '(:error)))) :error)
(prueba "rtos por defecto (LUPREC 4)" (rtos 15) "15.0000")
(prueba "rtos 2 2" (rtos 3.14159 2 2) "3.14")
(prueba "rtos científico" (rtos 1234.56 1 3) "1.235E+03")
(prueba "atof / atoi" (list (atof "2.5m") (atoi "12abc")) '(2.5d0 12))
(prueba "polar 2D" (polar '(1 1) (/ pi 2) 2) '(1d0 3d0))
(prueba "polar conserva z" (polar '(0 0 5) 0 1) '(1d0 0d0 5d0))
(prueba "distance 3D" (distance '(0 0 0) '(1 2 2)) 3d0)
(prueba "angle en [0, 2π)" (angle '(0 0) '(0 -1)) (* 1.5 pi))
(prueba "angtos en grados" (angtos (/ pi 4)) "45")
(prueba "inters" (inters '(0 0) '(2 2) '(0 2) '(2 0)) '(1d0 1d0 0d0))
(prueba "inters fuera del tramo" (inters '(0 0) '(1 1) '(3 0) '(3 5)) nil)
(prueba "inters infinitas" (inters '(0 0) '(1 1) '(3 0) '(3 5) nil) '(3d0 3d0 0d0))
(prueba "substr" (substr "HEKATAN" 2 3) "EKA")
(prueba "repeat/foreach devuelven el último" (list (let ((i 0)) (repeat 3 (setq i (1+ i)))) (foreach x '(1 2 3) (* x 10))) '(3 30))
;; ejecutar AutoLISP: (princ), defun con / locales, lambda citada, \n en cadenas
(prueba "hk-al-ejecuta: AutoLISP de verdad"
        (with-output-to-string (*standard-output*)
          (hk-al-ejecuta "(defun doble (a / b) (setq b (* 2 a)) b) (setq k 3)
                          (princ (strcat \"x\\n\" (itoa (doble 4)) \" \" (itoa (apply '+ (mapcar '(lambda (x) (* k x)) '(1 2))))))
                          (princ)"))
        (format nil "x~%8 9~%"))
(prueba "un error no para el resto"
        (let ((s (with-output-to-string (*standard-output*) (hk-al-ejecuta "(car 5) (princ 1)"))))
          (list (subseq s 0 7) (subseq s (- (length s) 2))))
        (list "; error" (format nil "1~%")))
;; 3D: POLYLINE compleja y 3DFACE
(hk-al-nuevo)
(entmake '((0 . "POLYLINE") (66 . 1) (70 . 8) (10 0 0 0)))
(entmake '((0 . "VERTEX") (10 0 0 0) (70 . 32)))
(entmake '((0 . "VERTEX") (10 1 2 2) (70 . 32)))
(prueba "SEQEND cierra la polilínea" (entmake '((0 . "SEQEND"))) '((0 . "SEQEND")))
(prueba "entlast = la cabecera" (cdr (assoc 0 (entget (entlast)))) "POLYLINE")
(prueba "entnext entra a los VERTEX" (cdr (assoc 10 (entget (entnext (entlast))))) '(0d0 0d0 0d0))
(prueba "ssget no ve los VERTEX" (sslength (ssget "_X")) 1)
(prueba "longitud 3D" (longitud (entlast)) 3d0)
(prueba "VERTEX suelto → nil" (entmake '((0 . "VERTEX") (10 0 0 0))) nil)
(prueba "3DFACE: 13 = 12 si falta" (cdr (assoc 13 (entget (entmakex '((0 . "3DFACE") (10 0 0 0) (11 1 0 0) (12 1 1 1))))))
        '(1d0 1d0 1d0))
;; capa simple y medir
(hk-al-nuevo)
(prueba "rect → área" (area (rect '(0 0) 2 3)) 6d0)
(prueba "curva de una expresión simbólica" (length (vertices (curva '(* x x) -1 1 :n 4))) 5)
(prueba "área bajo x² en [0,1] por el polígono" (let ((b (loop for i from 0 to 400 collect (let ((x (/ i 400d0))) (list x (* x x))))))
                                                 (area (achurado (append '((0 0)) b '((1 0)))))) (+ 1/3 (/ 1d0 (* 6 400 400))))
(prueba "desplazar / entmod mueve" (let ((d (linea '(0 0) '(1 0)))) (entmod (desplazar d 0 2)) (cdr (assoc 10 (entget (cdr (assoc -1 d)))))) '(0d0 2d0 0d0))
(prueba "círculo: área" (area (circulo '(0 0) 1)) pi)
(prueba "formula = TEXT con estilo HKMATH" (cdr (assoc 7 (formula '(0 0) '(+ (* 2 x) 3) :nombre "f'(x)"))) "HKMATH")
(prueba "formula: texto de la expresión" (cdr (assoc 1 (formula '(0 0) '(+ (* 2 x) 3) :nombre "f'(x)"))) "f'(x) = 2*x + 3")
(prueba "exporta: forma exacta → número"
        (with-output-to-string (*standard-output*) (hk-al-exporta "A" '(/ 39 4)))
        (format nil "~cX~cA~c9.75~%" (code-char 28) (code-char 31) (code-char 31)))
(format t "~d/~d OK~%" *ok* (+ *ok* *mal*))
