# -*- coding: utf-8 -*-
"""Genera la hoja Hekatan LISP «Placa base de columna tubular por elementos finitos» (ejemplos/144 …).

Modelo (tipo CBFEM, como lo plantea IDEA StatiCa, sin usar su programa ni su telemetría):
  · placa base y paredes del tubo (SHS) con el elemento de cáscara ShellMITC4 de la hoja 72 (6 gdl por nudo, validado contra OpenSees);
  · la SOLDADURA tubo-placa = nudos compartidos en el borde del tubo (unión rígida); su esfuerzo se lee como fuerza por unidad de longitud;
  · el PEDESTAL de hormigón = muelles Winkler verticales solo a compresión en cada nudo de la placa;
  · los PERNOS de anclaje = muelles verticales solo a tracción (EA/L) en cuatro nudos;
  · carga axial N y momento M en la cabeza del tubo, repartidos por la distribución lineal de esfuerzos de la sección.
Unidades kN, m, kPa. Los mismos datos (params.json) los usa el modelo de Abaqus (abaqus_inp.py).
"""
import json, os, re

AQUI = os.path.dirname(os.path.abspath(__file__))
EJ = os.path.join(AQUI, "..", "..", "ejemplos")
F72 = [f for f in os.listdir(EJ) if f.startswith("72 ")][0]

P = dict(
    xs=[-0.2, -0.125, -0.095, -0.0475, 0.0, 0.0475, 0.095, 0.125, 0.2],   # líneas de la malla de la placa (x = y)
    t_p=0.025, E=2.1e8, nu=0.3,
    t_c=0.010, nz=5, H=0.10,                                              # tubo SHS 200×200×10 (línea media 190), 5 filas de 20 mm
    bolt=0.125, A_b=353e-6, L_b=0.30,                                      # pernos M24 a ±125 mm
    k_c=6.0e7,                                                             # Winkler del hormigón [kN/m³]
    N=300.0, M=40.0,                                                      # compresión [kN] y momento alrededor de x [kN·m]
)
P["k_b"] = P["E"] * P["A_b"] / P["L_b"]
json.dump(P, open(os.path.join(AQUI, "params.json"), "w"), indent=1)


def funcs():
    L = open(os.path.join(EJ, F72), encoding="utf8").read().splitlines()
    out = []
    i = next(k for k, l in enumerate(L) if l.startswith("function d = LovelyEig"))
    j = next(k for k in range(i, len(L)) if L[k] == "end")
    out += L[i:j + 1] + [""]
    i = next(k for k, l in enumerate(L) if l.startswith("function K = mitc4_K"))
    j = next(k for k in range(i, len(L)) if L[k] == "end")
    out += L[i:j + 1]
    return "\n".join(out)


def num(v):
    return repr(float(v))


H = []
a = H.append
a("# Placa base de una columna tubular por elementos finitos: cáscaras, pernos, hormigón y soldadura")
a("#numerico")
a("")
a("#: **Qué se calcula.** La unión de una columna **tubular** (SHS 200 × 200 × 10) con su **placa base** de 400 × 400 × 25 mm sobre un **pedestal** de hormigón, con **cuatro pernos** M24 y la **soldadura** del tubo a la placa, bajo compresión y momento. Se resuelve por **elementos finitos de cáscara**, como lo plantea el método de componentes por elementos finitos (CBFEM) de IDEA StatiCa: placa y tubo son cáscaras, el hormigón son muelles solo a compresión, los pernos son muelles solo a tracción y la soldadura une el tubo a la placa.")
a("#: **Por qué importa.** El método de componentes por fórmulas reparte la carga con hipótesis (T equivalente, ancho efectivo). Aquí la placa se **flexiona**, **se despega** del hormigón donde el momento levanta y los **pernos** entran solo cuando hace falta: el reparto sale del cálculo.")
a("#: **Cómo.** Elemento ShellMITC4 de la hoja 72 (6 gdl por nudo, validado contra OpenSees). Soldadura = nudos compartidos en el borde del tubo; su fuerza por unidad de longitud se lee de la rigidez del tubo. Hormigón: muelles de Winkler verticales en cada nudo de la placa, activos solo en compresión; pernos: EA/L, activos solo en tracción. Se itera el conjunto activo hasta que no cambie.")
a("#: **Juez.** **Abaqus** (shell S4 con las mismas mallas, muelles no lineales y el mismo reparto de cargas): se comparan los desplazamientos de los 161 nudos. Sin IDEA StatiCa: se ha bloqueado su telemetría y no se apoya en su licencia.")
a("#: **Unidades.** kN, m y kPa.")
a("")
a("## 1 · Datos")
a("")
a("#: **Material** (acero S355):")
a("E = %s 'módulo de elasticidad del acero [kPa]" % num(P["E"]))
a("ν = %s 'coeficiente de Poisson" % num(P["nu"]))
a("#: **Geometría.** Placa de 0.400 m de lado y 25 mm; tubo SHS 200 × 200 × 10 (se modela su línea media, 190 × 190 mm); se modelan 100 mm de altura del tubo.")
a("t_p = %s 'espesor de la placa [m]" % num(P["t_p"]))
a("t_c = %s 'espesor de la pared del tubo [m]" % num(P["t_c"]))
a("H_c = %s 'altura del tubo modelada [m]" % num(P["H"]))
a("n_z = %d 'filas de elementos en la altura del tubo" % P["nz"])
a("xs = [%s] 'líneas de la malla de la placa (en x y en y) [m]" % "; ".join(num(v) for v in P["xs"]))
a("#: **Pernos y hormigón:**")
a("a_b = %s 'los cuatro pernos están en x, y = ± a_b [m]" % num(P["bolt"]))
a("A_b = %s 'área resistente de un perno M24 [m2]" % num(P["A_b"]))
a("L_b = %s 'longitud libre del perno [m]" % num(P["L_b"]))
a("k_b = E·A_b/L_b 'rigidez axial de un perno, solo tracción [kN/m]")
a("k_c = %s 'módulo de balasto del pedestal de hormigón, solo compresión [kN/m3]" % num(P["k_c"]))
a("#: **Cargas en la cabeza del tubo** (compresión y momento alrededor del eje x):")
a("N_c = %s 'carga axial de compresión [kN]" % num(P["N"]))
a("M_x = %s 'momento alrededor de x [kN·m]" % num(P["M"]))
a("")
a("## 2 · El elemento de cáscara (ShellMITC4, hoja 72)")
a("")
a("#: Sección elástica membrana + placa de espesor t, con cortante transversal κ = 5/6:")
a("#hide")
a(funcs())
a("function dd = seccion(E, nu, t)")
a("  Mm = E/(1 - nu^2)·t")
a("  G = 0.5·E/(1 + nu)·t")
a("  Gs = G·(5/6)")
a("  D = E·t^3/12/(1 - nu^2)")
a("  dd = zeros(8, 8)")
a("  dd(1, 1) = Mm")
a("  dd(2, 2) = Mm")
a("  dd(1, 2) = nu·Mm")
a("  dd(2, 1) = nu·Mm")
a("  dd(3, 3) = G")
a("  dd(4, 4) = -D")
a("  dd(5, 5) = -D")
a("  dd(4, 5) = -nu·D")
a("  dd(5, 4) = -nu·D")
a("  dd(6, 6) = -0.5·D·(1 - nu)")
a("  dd(7, 7) = Gs")
a("  dd(8, 8) = Gs")
a("end")
a("#show")
a("dd_p = seccion(E, ν, t_p) 'sección de la placa")
a("dd_c = seccion(E, ν, t_c) 'sección de la pared del tubo")
a("")
a("## 3 · La malla")
a("")
a("#: **Placa:** 8 × 8 elementos (81 nudos, z = 0). **Tubo:** 16 tramos de perímetro por 5 filas (80 nudos más, los de la fila de abajo son los de la placa: ahí está la soldadura). Los nudos del perímetro del tubo caen en las líneas ± 0.095 m de la malla de la placa.")
a("n_x = 9 'líneas por lado de la placa")
a("n_p = 81 'nudos de la placa")
a("n_n = 161 'nudos totales")
a("n_e = 144 'elementos: 64 de placa y 80 de tubo")
a("#hide")
a("Xn = zeros(n_n, 3)")
a("for j = 1:n_x")
a("  for i = 1:n_x")
a("    q = (j - 1)·n_x + i")
a("    Xn(q, 1) = xs(i)")
a("    Xn(q, 2) = xs(j)")
a("  end")
a("end")
a("#: Perímetro del tubo, de a_c = −0.095: lado inferior (+x), derecho (+y), superior (−x), izquierdo (−y). Índices de línea 3 … 7 de xs.")
a("pi_x = [3, 4, 5, 6, 7, 7, 7, 7, 7, 6, 5, 4, 3, 3, 3, 3] 'índice de línea en x de cada punto del perímetro")
a("pi_y = [3, 3, 3, 3, 3, 4, 5, 6, 7, 7, 7, 7, 7, 6, 5, 4] 'índice de línea en y")
a("Pn = zeros(16, 1)")
a("for k = 1:16")
a("  Pn(k) = (pi_y(k) - 1)·n_x + pi_x(k)")
a("end")
a("for l = 1:n_z")
a("  for k = 1:16")
a("    q = n_p + (l - 1)·16 + k")
a("    Xn(q, 1) = xs(pi_x(k))")
a("    Xn(q, 2) = xs(pi_y(k))")
a("    Xn(q, 3) = H_c·l/n_z")
a("  end")
a("end")
a("En = zeros(n_e, 4)")
a("for j = 1:8")
a("  for i = 1:8")
a("    e = (j - 1)·8 + i")
a("    q = (j - 1)·n_x + i")
a("    En(e, :) = [q, q + 1, q + n_x + 1, q + n_x]")
a("  end")
a("end")
a("function q = nodo_tubo(l, k, Pn, n_p)")
a("  if l == 0")
a("    q = Pn(k)")
a("  else")
a("    q = n_p + (l - 1)·16 + k")
a("  end")
a("end")
a("e = 64")
a("for l = 1:n_z")
a("  for k = 1:16")
a("    k2 = mod(k, 16) + 1")
a("    e = e + 1")
a("    En(e, :) = [nodo_tubo(l - 1, k, Pn, n_p), nodo_tubo(l - 1, k2, Pn, n_p), nodo_tubo(l, k2, Pn, n_p), nodo_tubo(l, k, Pn, n_p)]")
a("  end")
a("end")
a("#show")
a("Xn_b = Xn(1:3, :) 'primeros nudos: z = 0, en la esquina de la placa")
a("")
a("## 4 · Ensamblaje de la rigidez")
a("")
a("#: Seis grados de libertad por nudo: u_x, u_y, u_z, θ_x, θ_y, θ_z (los del nudo q son 6(q − 1) + 1 … 6). Cada elemento suma su matriz de 24 × 24 en las filas y columnas de sus cuatro nudos; los nudos compartidos del borde del tubo son la **soldadura**.")
a("n_g = 6·n_n 'grados de libertad")
a("#hide")
a("K = zeros(n_g, n_g)")
a("function g = gdl(q)")
a("  g = 6·(q - 1) + (1:6)")
a("end")
a("for e = 1:n_e")
a("  q = En(e, :)")
a("  Xe = [Xn(q(1), :); Xn(q(2), :); Xn(q(3), :); Xn(q(4), :)]")
a("  if e <= 64")
a("    Ke = mitc4_K(Xe, dd_p)")
a("  else")
a("    Ke = mitc4_K(Xe, dd_c)")
a("  end")
a("  g = [gdl(q(1)), gdl(q(2)), gdl(q(3)), gdl(q(4))]")
a("  K(g, g) = K(g, g) + Ke")
a("end")
a("#show")
a("")
a("## 5 · Los apoyos: hormigón solo a compresión y pernos solo a tracción")
a("")
a("#: Cada nudo de la placa lleva un muelle vertical de rigidez k_c por su **área tributaria**. Los pernos están en los cuatro nudos (±a_b, ±a_b), con rigidez k_b. Para que el modelo no flote en el plano: se fijan u_x y u_y en el centro de la placa y u_y en el centro del borde x = +0.2.")
a("#hide")
a("kc_i = zeros(n_p, 1)")
a("for j = 1:n_x")
a("  for i = 1:n_x")
a("    i0 = max(i - 1, 1)")
a("    i1 = min(i + 1, n_x)")
a("    j0 = max(j - 1, 1)")
a("    j1 = min(j + 1, n_x)")
a("    kc_i((j - 1)·n_x + i) = k_c·(xs(i1) - xs(i0))/2·(xs(j1) - xs(j0))/2")
a("  end")
a("end")
a("kb_i = zeros(n_p, 1)")
a("nb = [(2 - 1)·n_x + 2, (2 - 1)·n_x + 8, (8 - 1)·n_x + 2, (8 - 1)·n_x + 8]")
a("for m = 1:4")
a("  kb_i(nb(m)) = k_b")
a("end")
a("#show")
a("#: Nudos de los pernos:")
a("nb")
a("")
a("## 6 · Las cargas")
a("")
a("#: Se reparten en los 16 nudos de la cabeza del tubo con la distribución lineal de esfuerzos σ = −N/A − M·y/I de la sección (A = Σ a_k, I = Σ a_k·y_k², a_k = longitud tributaria × t_c): la resultante es exactamente N y M.")
a("#hide")
a("ell = 0.0475 'longitud tributaria de cada nudo del perímetro [m]")
a("a_k = ell·t_c 'área de pared tributaria de cada nudo [m2]")
a("A_t = 16·a_k 'área de la sección del tubo [m2]")
a("I_t = 0")
a("for k = 1:16")
a("  I_t = I_t + a_k·xs(pi_y(k))^2")
a("end")
a("F = zeros(n_g, 1)")
a("for k = 1:16")
a("  q = n_p + (n_z - 1)·16 + k")
a("  sg = -N_c/A_t - M_x·xs(pi_y(k))/I_t")
a("  F(6·(q - 1) + 3) = sg·a_k")
a("end")
a("#show")
a("A_t 'área del tubo [m2]")
a("I_t 'inercia discreta del tubo [m4]")
a("S_F = sum(F) 'resultante vertical de las cargas [kN] (debe ser −N)")
a("")
a("## 7 · Solución: conjunto activo de muelles")
a("")
a("#: Se resuelve con todos los muelles de hormigón activos y ningún perno; después se **apagan** los de hormigón que suben (u_z > 0) y se **encienden** los pernos que suben, y se repite hasta que el conjunto no cambia.")
a("#hide")
a("c_on = ones(n_p, 1)")
a("b_on = zeros(n_p, 1)")
a("iters = 0")
a("cambia = 1")
a("U = zeros(n_g, 1)")
a("while cambia > 0 && iters < 30")
a("  Kt = K")
a("  for q = 1:n_p")
a("    d3 = 6·(q - 1) + 3")
a("    Kt(d3, d3) = Kt(d3, d3) + c_on(q)·kc_i(q) + b_on(q)·kb_i(q)")
a("  end")
a("  % apoyos en el plano: centro (q = 41): u_x, u_y; centro del borde x = +0.2 (q = 45): u_y")
a("  for d = [6·(41 - 1) + 1, 6·(41 - 1) + 2, 6·(45 - 1) + 2]")
a("    Kt(d, :) = 0")
a("    Kt(:, d) = 0")
a("    Kt(d, d) = 1")
a("  end")
a("  Ft = F")
a("  for d = [6·(41 - 1) + 1, 6·(41 - 1) + 2, 6·(45 - 1) + 2]")
a("    Ft(d) = 0")
a("  end")
a("  U = clsolve(Kt, Ft)")
a("  cambia = 0")
a("  for q = 1:n_p")
a("    uz = U(6·(q - 1) + 3)")
a("    if c_on(q) == 1 && uz > 0")
a("      c_on(q) = 0")
a("      cambia = cambia + 1")
a("    end")
a("    if c_on(q) == 0 && uz < 0")
a("      c_on(q) = 1")
a("      cambia = cambia + 1")
a("    end")
a("    if kb_i(q) > 0")
a("      if b_on(q) == 0 && uz > 0")
a("        b_on(q) = 1")
a("        cambia = cambia + 1")
a("      end")
a("      if b_on(q) == 1 && uz < 0")
a("        b_on(q) = 0")
a("        cambia = cambia + 1")
a("      end")
a("    end")
a("  end")
a("  iters = iters + 1")
a("end")
a("#show")
a("iters 'iteraciones del conjunto activo")
a("")
a("## 8 · Resultados")
a("")
a("#hide")
a("Rc = zeros(n_p, 1)")
a("Rb = zeros(n_p, 1)")
a("uz_p = zeros(n_p, 1)")
a("for q = 1:n_p")
a("  uz_p(q) = U(6·(q - 1) + 3)")
a("  Rc(q) = -c_on(q)·kc_i(q)·uz_p(q)")
a("  Rb(q) = -b_on(q)·kb_i(q)·uz_p(q)")
a("end")
a("pres = zeros(n_p, 1)")
a("for q = 1:n_p")
a("  pres(q) = Rc(q)/(kc_i(q)/k_c)")
a("end")
a("#show")
a("R_conc = sum(Rc) 'reacción total del hormigón (hacia arriba) [kN]")
a("T_b = sum(Rb) 'fuerza total de los pernos (hacia abajo: negativa) [kN]")
a("equil = R_conc + T_b + S_F 'equilibrio vertical: debe ser 0 [kN]")
a("sig_max = max(pres)/1000 'presión máxima de contacto [MPa]")
a("n_lev = n_p - sum(c_on) 'nudos de la placa levantados del hormigón")
a("T_1 = -min(Rb) 'tracción del perno más cargado [kN]")
a("#: **Pedestal.** Resistencia de contacto del hormigón f_cd = 25/1.5 y factor de confinamiento k_j = √(A_pedestal/A_placa) ≤ 3, con el pedestal de 0.50 × 0.50 m:")
a("f_cd = 25/1.5 'resistencia de cálculo del hormigón [MPa]")
a("k_j = min(3, sqrt(0.5^2/0.4^2)) 'factor de confinamiento")
a("rat_c = sig_max/(k_j·f_cd) 'aprovechamiento del contacto")
a("#: **Perno.** Resistencia a tracción de un M24 de clase 8.8: 0.9·f_ub·A_s/γ_M2 con f_ub = 800 MPa y γ_M2 = 1.25:")
a("F_tRd = 0.9·800000·A_b/1.25 'resistencia a tracción de un perno [kN]")
a("rat_b = T_1/F_tRd 'aprovechamiento del perno")
a("")
a("## 9 · La soldadura tubo-placa")
a("")
a("#: Los elementos del tubo de la fila de abajo transmiten a la placa, por cada nudo del perímetro, tres fuerzas (axial y dos de corte). Dividida por la longitud tributaria da la **fuerza por unidad de longitud** de soldadura q_w. El garganta necesaria para una soldadura en ángulo exterior (EN 1993-1-8, método simplificado) es a = q_w / f_vw,d con f_vw,d = f_u/(√3·β_w·γ_M2), f_u = 510 MPa, β_w = 0.90 (S355), γ_M2 = 1.25:")
a("#hide")
a("Fw = zeros(16, 3)")
a("for e = 65:80")
a("  q = En(e, :)")
a("  Xe = [Xn(q(1), :); Xn(q(2), :); Xn(q(3), :); Xn(q(4), :)]")
a("  Ke = mitc4_K(Xe, dd_c)")
a("  g = [gdl(q(1)), gdl(q(2)), gdl(q(3)), gdl(q(4))]")
a("  ug = zeros(24, 1)")
a("  for r = 1:24")
a("    ug(r) = U(g(r))")
a("  end")
a("  fe = Ke·ug")
a("  k1 = e - 64")
a("  k2 = mod(k1, 16) + 1")
a("  for c3 = 1:3")
a("    Fw(k1, c3) = Fw(k1, c3) + fe(c3)")
a("    Fw(k2, c3) = Fw(k2, c3) + fe(6 + c3)")
a("  end")
a("end")
a("qw = zeros(16, 1)")
a("for k = 1:16")
a("  qw(k) = sqrt(Fw(k, 1)^2 + Fw(k, 2)^2 + Fw(k, 3)^2)/ell")
a("end")
a("#show")
a("S_wz = sum(Fw(:, 3)) 'suma de las fuerzas verticales que baja la soldadura al plato [kN]")
a("q_w = max(qw) 'fuerza máxima por unidad de longitud de soldadura [kN/m]")
a("f_vwd = 510000/(sqrt(3)·0.9·1.25) 'resistencia de cálculo a cortante de la soldadura [kPa]")
a("a_req = q_w/f_vwd·1000 'garganta necesaria [mm]")
a("")
a("## 10 · El método analítico de AISC (Guía de Diseño 1): la placa como voladizo")
a("")
a("#: **La idea.** AISC trata la placa como un **voladizo** que sale de la cara del tubo: la presión del hormigón (un bloque uniforme de resistencia f_p) la dobla hacia arriba; si el momento es grande, la placa se levanta de un lado y la **tracción de los pernos** la dobla hacia abajo. El espesor sale de pedir que el momento por unidad de ancho no pase de la resistencia plástica t²·F_y/4. Para una columna **hueca cuadrada o rectangular** la Guía de Diseño 1 mide los voladizos hasta 0.95 veces el lado del tubo: m = (N − 0.95·d)/2 en el plano del momento y n = (B − 0.95·b)/2 en el otro; manda el mayor.")
a("#: **Datos del método** (LRFD): placa N × B = 0.40 × 0.40 m, tubo de 0.200 × 0.200 m (d × b), F_y = 355 MPa, f′_c = 25 MPa sobre un pedestal de 0.50 × 0.50 m, pernos a f = 0.125 m del eje:")
a("N_p = 0.4 'dimensión de la placa en el plano del momento [m]")
a("B_p = 0.4 'ancho de la placa [m]")
a("d_t = 0.2 'lado del tubo en el plano del momento [m]")
a("b_t = 0.2 'lado del tubo en el otro sentido [m]")
a("F_y = 355000 'límite elástico de la placa [kPa]")
a("fc_p = 25000 'resistencia del hormigón f′_c [kPa]")
a("A_ped = 0.5·0.5 'área del pedestal [m2]")
a("f_b = 0.125 'distancia del eje a los pernos [m]")
a("#: **Resistencia de contacto** (φ_c = 0.65; el factor de confinamiento √(A₂/A₁) no pasa de 2):")
a("f_pmax = 0.65·0.85·fc_p·min(2, sqrt(A_ped/(N_p·B_p))) 'presión máxima de contacto de cálculo [kPa]")
a("q_max = f_pmax·B_p 'carga máxima por metro de la placa [kN/m]")
a("m_c = (N_p - 0.95·d_t)/2 'voladizo en el plano del momento, hasta 0.95 del lado del tubo [m]")
a("n_c = (B_p - 0.95·b_t)/2 'voladizo en el otro sentido [m]")
a("u_t = f_b - 0.95·d_t/2 'del perno a la cara del tubo [m]")
a("#hide")
a("function R = aisc(P, M, N_p, B_p, f_b, f_pmax, q_max, m_c, u_t, F_y)")
a("  e = M/P")
a("  e_cr = N_p/2 - P/(2·q_max)")
a("  if e <= e_cr")
a("    Y = N_p - 2·e")
a("    T = 0")
a("    f_p = P/(Y·B_p)")
a("  else")
a("    Y = (f_b + N_p/2) - sqrt((f_b + N_p/2)^2 - 2·P·(e + f_b)/q_max)")
a("    T = q_max·Y - P")
a("    f_p = f_pmax")
a("  end")
a("  if Y >= m_c")
a("    Mc = f_p·m_c^2/2")
a("  else")
a("    Mc = f_p·Y·(m_c - Y/2)")
a("  end")
a("  Mt = T·u_t/B_p")
a("  t_r = sqrt(4·max(Mc, Mt)/(0.9·F_y))")
a("  R = [e; e_cr; Y; T; f_p; Mc; Mt; t_r]")
a("end")
a("#show")
a("A_r = aisc(N_c, M_x, N_p, B_p, f_b, f_pmax, q_max, m_c, u_t, F_y) 'e · e_crít · Y · T · f_p · M_contacto · M_perno · t_req")
a("#: **Excentricidad.** e = M/P se compara con la crítica e_crít = N/2 − P/(2·q_max): por debajo, la placa solo comprime (longitud de apoyo Y = N − 2e, bloque uniforme f_p = P/(Y·B)); por encima, la placa se levanta, los pernos de ese lado trabajan con T = q_max·Y − P y Y sale de la ecuación de momentos respecto de los pernos.")
a("e_a = A_r(1) 'excentricidad e = M/P [m]")
a("e_crit = A_r(2) 'excentricidad crítica [m]")
a("Y_a = A_r(3) 'longitud de apoyo [m]")
a("T_a = A_r(4) 'tracción total de los pernos de un lado [kN]")
a("t_a = A_r(8)·1000 'espesor de placa necesario por AISC [mm]")
a("")
a("## 11 · Lo mismo por elementos finitos, barriendo el momento")
a("")
a("#: Con el modelo por elementos finitos (el de las secciones 1 a 9, que es el planteamiento de IDEA StatiCa) se repite el cálculo para momentos de 0 a 90 kN·m con la misma carga axial. De cada solución se leen los **mismos números** que da AISC: la tracción de los pernos, el momento de voladizo por unidad de ancho en la cara del tubo (a partir de las reacciones del hormigón y de los pernos) y el espesor que resulta de él.")
a("#hide")
a("function Fc = carga(N, M, pi_y, xs, n_p, n_z, n_g, t_c)")
a("  ell = 0.0475")
a("  a_k = ell·t_c")
a("  A_t = 16·a_k")
a("  I_t = 0")
a("  for k = 1:16")
a("    I_t = I_t + a_k·xs(pi_y(k))^2")
a("  end")
a("  Fc = zeros(n_g, 1)")
a("  for k = 1:16")
a("    q = n_p + (n_z - 1)·16 + k")
a("    Fc(6·(q - 1) + 3) = (-N/A_t - M·xs(pi_y(k))/I_t)·a_k")
a("  end")
a("end")
a("function Uc = resuelve(K, Fc, kc_i, kb_i, n_p, n_g)")
a("  c_on = ones(n_p, 1)")
a("  b_on = zeros(n_p, 1)")
a("  cambia = 1")
a("  iters = 0")
a("  Uc = zeros(n_g, 1)")
a("  while cambia > 0 && iters < 30")
a("    Kt = K")
a("    for q = 1:n_p")
a("      d3 = 6·(q - 1) + 3")
a("      Kt(d3, d3) = Kt(d3, d3) + c_on(q)·kc_i(q) + b_on(q)·kb_i(q)")
a("    end")
a("    for d = [6·(41 - 1) + 1, 6·(41 - 1) + 2, 6·(45 - 1) + 2]")
a("      Kt(d, :) = 0")
a("      Kt(:, d) = 0")
a("      Kt(d, d) = 1")
a("    end")
a("    Ft = Fc")
a("    for d = [6·(41 - 1) + 1, 6·(41 - 1) + 2, 6·(45 - 1) + 2]")
a("      Ft(d) = 0")
a("    end")
a("    Uc = clsolve(Kt, Ft)")
a("    cambia = 0")
a("    for q = 1:n_p")
a("      uz = Uc(6·(q - 1) + 3)")
a("      if c_on(q) == 1 && uz > 0")
a("        c_on(q) = 0")
a("        cambia = cambia + 1")
a("      end")
a("      if c_on(q) == 0 && uz < 0")
a("        c_on(q) = 1")
a("        cambia = cambia + 1")
a("      end")
a("      if kb_i(q) > 0")
a("        if b_on(q) == 0 && uz > 0")
a("          b_on(q) = 1")
a("          cambia = cambia + 1")
a("        end")
a("        if b_on(q) == 1 && uz < 0")
a("          b_on(q) = 0")
a("          cambia = cambia + 1")
a("        end")
a("      end")
a("    end")
a("    iters = iters + 1")
a("  end")
a("end")
a("function R = post(Uc, kc_i, kb_i, xs, n_p, n_x, B_p)")
a("  Rc_t = 0")
a("  Tb = 0")
a("  nl = 0")
a("  Mp = 0")
a("  Mn = 0")
a("  for j = 1:n_x")
a("    for i = 1:n_x")
a("      q = (j - 1)·n_x + i")
a("      uz = Uc(6·(q - 1) + 3)")
a("      rc = 0")
a("      rb = 0")
a("      if uz < 0")
a("        rc = -kc_i(q)·uz")
a("      else")
a("        nl = nl + 1")
a("        if kb_i(q) > 0")
a("          rb = kb_i(q)·uz")
a("        end")
a("      end")
a("      Rc_t = Rc_t + rc")
a("      Tb = Tb + rb")
a("      if xs(j) > 0.095 + 1e-9")
a("        Mp = Mp + (rc - rb)·(xs(j) - 0.095)")
a("      end")
a("      if xs(j) < -0.095 - 1e-9")
a("        Mn = Mn + (rc - rb)·(-xs(j) - 0.095)")
a("      end")
a("    end")
a("  end")
a("  R = [Rc_t; Tb; nl; abs(Mp)/B_p; abs(Mn)/B_p]")
a("end")
a("ms = [0; 10; 20; 30; 40; 50; 60; 70; 80; 90] 'momentos del barrido [kN·m]")
a("n_m = 10")
a("Tm = zeros(n_m, 2)")
a("Tr = zeros(n_m, 2)")
a("Ym = zeros(n_m, 2)")
a("TmA = zeros(n_m, 2)")
a("for s = 1:n_m")
a("  Fs = carga(N_c, ms(s), pi_y, xs, n_p, n_z, n_g, t_c)")
a("  Us = resuelve(K, Fs, kc_i, kb_i, n_p, n_g)")
a("  Ps = post(Us, kc_i, kb_i, xs, n_p, n_x, B_p)")
a("  As = aisc(N_c, ms(s), N_p, B_p, f_b, f_pmax, q_max, m_c, u_t, F_y)")
a("  Tm(s, 1) = ms(s)")
a("  Tm(s, 2) = Ps(2)")
a("  Tr(s, 1) = ms(s)")
a("  Tr(s, 2) = 1000·sqrt(4·max(Ps(4), Ps(5))/(0.9·F_y))")
a("  Ym(s, 1) = ms(s)")
a("  Ym(s, 2) = 1000·As(8)")
a("  TmA(s, 1) = ms(s)")
a("  TmA(s, 2) = As(4)")
a("end")
a("#show")
a("")
a("#: **Gráfica 1. Tracción total de los pernos de un lado frente al momento** (N = %g kN). Los puntos azules son el cálculo por elementos finitos (placa elástica con muelles); los naranjas, el método de AISC (bloque rígido-plástico). AISC no da tracción hasta que e = M/P pasa de e_crít; por elementos finitos la placa se **flexiona** y los pernos empiezan a trabajar antes, porque la presión no es un bloque uniforme sino que crece hacia el borde comprimido." % P["N"])
a("#fplot(FEM = Tm, AISC = TmA, [0 90])")
a("#: **Gráfica 2. Espesor de placa necesario frente al momento** (mm). Azul: el que sale del momento de voladizo leído en el modelo de elementos finitos; naranja: AISC. La placa real es de 25 mm.")
a("#fplot(FEM = Tr, AISC = Ym, [0 90])")
a("")
a("#: **Gráfica 3. La presión bajo la placa, a lo largo de su línea central, con M = 70 kN·m** (e = 0.233 m, mayor que la crítica: AISC ya da tracción en los pernos). Los puntos azules son la presión de contacto por elementos finitos (MPa); los naranjas, el bloque uniforme de AISC sobre la longitud de apoyo Y. El borde comprimido está en y = +0.2 m. Se ve la diferencia de fondo: AISC reparte la carga en un **bloque plano** y por eso necesita más espesor; por elementos finitos la presión **crece hacia el borde** y el momento de voladizo es menor.")
a("#hide")
a("U70 = resuelve(K, carga(N_c, 70, pi_y, xs, n_p, n_z, n_g, t_c), kc_i, kb_i, n_p, n_g)")
a("A70 = aisc(N_c, 70, N_p, B_p, f_b, f_pmax, q_max, m_c, u_t, F_y)")
a("Pc = zeros(n_x, 2)")
a("Pa = zeros(41, 2)")
a("for j = 1:n_x")
a("  q = (j - 1)·n_x + 5")
a("  Pc(j, 1) = xs(j)")
a("  Pc(j, 2) = max(0, -k_c·U70(6·(q - 1) + 3))/1000")
a("end")
a("for s = 1:41")
a("  ys = -0.2 + 0.01·(s - 1)")
a("  Pa(s, 1) = ys")
a("  if ys >= 0.2 - A70(3) - 1e-9")
a("    Pa(s, 2) = A70(5)/1000")
a("  end")
a("end")
a("#show")
a("Y_70 = A70(3) 'longitud de apoyo de AISC con M = 70 [m]")
a("T_70 = A70(4) 'tracción de AISC con M = 70 [kN]")
a("#fplot(FEM = Pc, AISC = Pa, [-0.2 0.2])")
a("")
a("## 12 · Comparación para el caso de la hoja (N = %g kN, M = %g kN·m)" % (P["N"], P["M"]))
a("")
a("#hide")
a("Pf = post(U, kc_i, kb_i, xs, n_p, n_x, B_p)")
a("#show")
a("T_fem = Pf(2) 'tracción total de los pernos (FEM) [kN]")
a("M_fem = max(Pf(4), Pf(5)) 'momento de voladizo por unidad de ancho (FEM) [kN·m/m]")
a("t_fem = 1000·sqrt(4·M_fem/(0.9·F_y)) 'espesor necesario (FEM) [mm]")
a("M_aisc = max(A_r(6), A_r(7)) 'momento de voladizo por unidad de ancho (AISC) [kN·m/m]")
a("#: **Qué dice cada método.** AISC: bloque uniforme de presión sobre la longitud de apoyo Y y, si e > e_crít, tracción en los pernos. Elementos finitos: la placa se deforma, la presión es lineal y los pernos se activan a medida que la placa los levanta. Los dos dan el espesor con la misma regla (voladizo plástico t² F_y/4 = M).")
a("#: **Qué comprobó Abaqus.** Con el mismo modelo, los pernos, el hormigón y los desplazamientos del modelo por elementos finitos coinciden con Abaqus (secciones anteriores); la diferencia con AISC es de método, no de cálculo.")
a("")
a("## 13 · La unión dibujada")
a("")
a("#: **Sección acotada** por el plano del momento: la placa de 25 mm sobre el pedestal, el tubo hueco de 200 mm y los pernos a 125 mm del eje. m es el voladizo de la placa hasta 0.95 del lado del tubo; u, la distancia del perno a esa cara.")
a("#dibujo(\"Placa base de columna tubular: sección por el plano del momento\", ud = m, escala = auto, cotas = m, ancho = 190, alto = 150)")
a("#  rect(-0.25, -0.40, 0.50, 0.40, \"gruesa\")")
a("#  rect(-0.20, 0, 0.40, t_p, \"gruesa\")")
a("#  achurado(-0.20, 0, 0.40, t_p, \"acero\")")
a("#  poligono(-0.1, t_p, -0.09, t_p, -0.09, 0.30, -0.1, 0.30, \"gruesa\")")
a("#  poligono(0.09, t_p, 0.1, t_p, 0.1, 0.30, 0.09, 0.30, \"gruesa\")")
a("#  linea(-0.125, -0.28, -0.125, 0.055, \"gruesa verde\")")
a("#  linea(0.125, -0.28, 0.125, 0.055, \"gruesa verde\")")
a("#  texto(0.0, 0.34, \"tubo hueco SHS 200 × 200 × 10\", 3, \"c\")")
a("#  texto(0.0, -0.46, \"pedestal de hormigón 0.50 × 0.50 m\", 3, \"c\")")
a("#  texto(0.19, -0.10, \"perno M24\", 2.6, \"i\", estilo = \"verde\")")
a("#  flecha(0.0, 0.52, 0.0, 0.32, \"rojo\")")
a("#  texto(0.02, 0.50, \"N = %g kN · M = %g kN·m\", 2.6, \"i\", estilo = \"rojo\")" % (P["N"], P["M"]))
a("#  cota(-0.20, -0.52, 0.20, -0.52, -0.04, \"0.400\")")
a("#  cota(0.1, 0.06, 0.2, 0.06, 0.03, \"m = 0.105\")")
a("#  cota(0.1, -0.22, 0.125, -0.22, -0.03, \"u = 0.030\")")
a("#  cota(0.0, -0.14, 0.125, -0.14, -0.03, \"f = 0.125\")")
a("#  cota(0.28, 0, 0.28, t_p, 0.03, \"25 mm\")")
a("#fin")
a("")
a("## 14 · Resumen")
a("")
a(("#: Con N = %g kN y M = %g kN·m (excentricidad %.3f m, mayor que a/6 = 0.067 m de la placa)" % (P["N"], P["M"], P["M"] / P["N"])) + ": la placa **se despega** por el lado traccionado, los pernos de ese lado trabajan, y el hormigón del lado comprimido soporta la carga concentrada.")
a("#: Resultado para comparar con Abaqus (sección siguiente del registro): desplazamiento vertical de los nudos de la placa, tracción de los pernos y reacciones.")
a("uz_min = min(uz_p)*1000 'desplazamiento vertical mínimo de la placa [mm]")
a("uz_max = max(uz_p)*1000 'desplazamiento vertical máximo de la placa [mm]")
a("#: Los 966 desplazamientos y giros (u_x, u_y, u_z, θ_x, θ_y, θ_z de cada nudo, en m y rad) para compararlos con Abaqus:")
a("U_f = U 'desplazamientos y giros de los 161 nudos")
open(os.path.join(EJ, "144 Placa base de columna tubular por elementos finitos - placa, tubo, pernos, hormigon y soldadura contra Abaqus.lisp"), "w", encoding="utf8", newline="\n").write("\n".join(H) + "\n")
print("hoja escrita")
