# -*- coding: utf-8 -*-
"""Genera las hojas Hekatan LISP de la «Placa base de columna tubular (hueca cuadrada o rectangular) por elementos finitos».

    python gen_hoja.py            → ejemplos/144 (SHS 200 × 200 × 10) y ejemplos/145 (RHS 250 × 150 × 8) + params_<caso>.json

Modelo (tipo CBFEM, como lo plantea IDEA StatiCa, sin usar su programa ni su telemetría):
  · placa base y paredes del tubo (SHS/RHS) con la cáscara ShellMITC4 de la hoja 72 (6 gdl por nudo, validada contra OpenSees);
  · SOLDADURA tubo-placa = nudos compartidos en el borde del tubo; su esfuerzo se lee como fuerza por unidad de longitud;
  · PEDESTAL de hormigón = muelles Winkler verticales solo a compresión en cada nudo de la placa;
  · PERNOS de anclaje = muelles verticales solo a tracción (EA/L) en cuatro nudos;
  · carga axial N y momento M (alrededor de x) en la cabeza del tubo, repartidos con la distribución lineal de esfuerzos de la sección;
  · comparación con el método analítico de AISC (Guía de Diseño 1: la placa como voladizo) y con Abaqus (S4 + muelles no lineales).
Unidades kN, m, kPa. Los mismos datos (params_<caso>.json) los usa abaqus_inp.py.
"""
import json, os, math

AQUI = os.path.dirname(os.path.abspath(__file__))
EJ = os.path.join(AQUI, "..", "..", "ejemplos")
F72 = [f for f in os.listdir(EJ) if f.startswith("72 ")][0]

CASOS = {
    "shs": dict(num=144, nombre="SHS 200 × 200 × 10", bx=0.200, dy=0.200, t_c=0.010, Lx=0.200, Ly=0.200, fx=0.125, fy=0.125,
                ped=(0.50, 0.50), N=300.0, M=40.0, Mfin=90.0, t_p=0.025,
                titulo="Placa base de columna tubular cuadrada (SHS) por elementos finitos - placa, tubo, pernos, hormigon y soldadura contra AISC y Abaqus"),
    "rhs": dict(num=145, nombre="RHS 250 × 150 × 8", bx=0.150, dy=0.250, t_c=0.008, Lx=0.175, Ly=0.225, fx=0.100, fy=0.150,
                ped=(0.50, 0.60), N=300.0, M=50.0, Mfin=100.0, t_p=0.025,
                titulo="Placa base de columna tubular rectangular (RHS) por elementos finitos - placa, tubo, pernos, hormigon y soldadura contra AISC y Abaqus"),
}
COMUN = dict(E=2.1e8, nu=0.3, nz=5, H=0.10, A_b=353e-6, L_b=0.30, k_c=6.0e7)


def derivados(C):
    P = dict(COMUN, **C)
    P["ax"] = (P["bx"] - P["t_c"]) / 2
    P["ay"] = (P["dy"] - P["t_c"]) / 2
    P["xs"] = [-P["Lx"], -P["fx"], -P["ax"], -P["ax"] / 2, 0.0, P["ax"] / 2, P["ax"], P["fx"], P["Lx"]]
    P["ys"] = [-P["Ly"], -P["fy"], -P["ay"], -P["ay"] / 2, 0.0, P["ay"] / 2, P["ay"], P["fy"], P["Ly"]]
    P["k_b"] = P["E"] * P["A_b"] / P["L_b"]
    return P


def funcs():
    L = open(os.path.join(EJ, F72), encoding="utf8").read().splitlines()
    out = []
    i = next(k for k, l in enumerate(L) if l.startswith("function d = LovelyEig"))
    j = next(k for k in range(i, len(L)) if L[k] == "end")
    out += L[i:j + 1] + [""]
    i = next(k for k, l in enumerate(L) if l.startswith("function K = mitc4_K"))
    j = next(k for k in range(i, len(L)) if L[k] == "end")
    out += L[i:j + 1]
    return "\n".join(out)


def num(v):
    return repr(float(v))


def vec(v):
    return "[" + "; ".join(num(x) for x in v) + "]"


COMP = {
    "shs": {"T": ("56.96", "57.07", "57.45"), "R": ("356.96", "357.07", "357.45"), "up": ("0.2869", "0.2939", "0.2957"),
            "dn": ("-0.1598", "-0.1607", "-0.1648"), "pb": ("0.1153", "0.1155", "0.1162"), "vm": ("105.20", "103.34"), "sw": ("81.96", "81.47")},
    "rhs": {"T": ("67.82", "67.96", "68.43"), "R": ("367.82", "367.96", "368.43"), "up": ("0.2652", "0.2697", "0.2713"),
            "dn": ("-0.1808", "-0.1822", "-0.1878"), "pb": ("0.1372", "0.1375", "0.1385"), "vm": ("108.90", "109.69"), "sw": ("85.06", "84.42")},
}

def hoja(clave):
    C = CASOS[clave]
    P = derivados(C)
    json.dump(P, open(os.path.join(AQUI, "params_%s.json" % clave), "w"), indent=1)
    H = []
    a = H.append
    nom = P["nombre"]
    forma = "cuadrada (SHS)" if abs(P["bx"] - P["dy"]) < 1e-9 else "rectangular (RHS)"
    Nl, Bl = 2 * P["Ly"], 2 * P["Lx"]
    pedA = P["ped"][0] * P["ped"][1]
    f_pmax = 0.65 * 0.85 * 25000 * min(2, math.sqrt(pedA / (Nl * Bl)))
    m_c = (Nl - 0.95 * P["dy"]) / 2
    n_c = (Bl - 0.95 * P["bx"]) / 2
    u_t = P["fy"] - 0.95 * P["dy"] / 2
    a("# Placa base de una columna tubular %s por elementos finitos: cáscaras, pernos, hormigón y soldadura, contra AISC y Abaqus" % forma)
    a("#numerico")
    a("")
    a("#: **Qué se calcula.** La unión de una columna **hueca %s** (%s) con su **placa base** de %.0f × %.0f × %.0f mm sobre un **pedestal** de hormigón de %.2f × %.2f m, con **cuatro pernos** M24 y la **soldadura** del tubo a la placa, bajo compresión y momento. Se resuelve de dos maneras: por **elementos finitos de cáscara**, como lo plantea el método de componentes por elementos finitos (CBFEM) de IDEA StatiCa, y por el **método analítico de AISC** (Guía de Diseño 1), que trata la placa como un voladizo." % (forma, nom, Bl * 1000, Nl * 1000, P["t_p"] * 1000, P["ped"][0], P["ped"][1]))
    a("#: **Por qué importa.** El método de componentes por fórmulas reparte la carga con hipótesis (bloque uniforme de presión, voladizo hasta la cara del tubo). Por elementos finitos la placa se **flexiona**, **se despega** del hormigón donde el momento levanta y los **pernos** entran solo cuando hace falta: el reparto sale del cálculo. Comparar los dos enseña dónde AISC es conservador.")
    a("#: **Cómo.** Elemento ShellMITC4 de la hoja 72 (6 gdl por nudo, teoría de Reissner-Mindlin: placa **gruesa**, con deformación por cortante, como el elemento de cáscara de IDEA StatiCa; validado contra OpenSees). Soldadura = nudos compartidos en el borde del tubo; su fuerza por unidad de longitud se lee de la rigidez del tubo. Hormigón: muelles de Winkler verticales en cada nudo de la placa, activos solo en compresión; pernos: EA/L, activos solo en tracción. Se itera el conjunto activo hasta que no cambie.")
    a("#: **Juez.** **Abaqus** (shell S4 con las mismas mallas, muelles no lineales y el mismo reparto de cargas): se comparan los desplazamientos de los 161 nudos, la tracción de los pernos y las fuerzas de soldadura. No se usa IDEA StatiCa: se ha bloqueado su telemetría y no se apoya en su licencia.")
    a("#: **Unidades.** kN, m y kPa.")
    a("")
    a("## 1 · Datos")
    a("")
    a("#: **Material** (acero S355):")
    a("E = %s 'módulo de elasticidad del acero [kPa]" % num(P["E"]))
    a("ν = %s 'coeficiente de Poisson" % num(P["nu"]))
    a("#: **Geometría.** Placa de %.3f × %.3f m y %.0f mm; tubo %s (se modela su línea media: %.3f × %.3f m); se modelan 100 mm de altura del tubo. El momento actúa en el plano del lado de %.0f mm (eje y); el lado comprimido es el de y positivo." % (Bl, Nl, P["t_p"] * 1000, nom, 2 * P["ax"], 2 * P["ay"], P["dy"] * 1000))
    a("t_p = %s 'espesor de la placa [m]" % num(P["t_p"]))
    a("t_c = %s 'espesor de la pared del tubo [m]" % num(P["t_c"]))
    a("H_c = %s 'altura del tubo modelada [m]" % num(P["H"]))
    a("n_z = %d 'filas de elementos en la altura del tubo" % P["nz"])
    a("xs = %s 'líneas de la malla de la placa en x [m]" % vec(P["xs"]))
    a("ys = %s 'líneas de la malla de la placa en y [m]" % vec(P["ys"]))
    a("#: **Pernos y hormigón:**")
    a("A_b = %s 'área resistente de un perno M24 [m2]" % num(P["A_b"]))
    a("L_b = %s 'longitud libre del perno [m]" % num(P["L_b"]))
    a("k_b = E·A_b/L_b 'rigidez axial de un perno, solo tracción [kN/m]")
    a("k_c = %s 'módulo de balasto del pedestal de hormigón, solo compresión [kN/m3]" % num(P["k_c"]))
    a("#: Los cuatro pernos están en x = ± %.3f m, y = ± %.3f m." % (P["fx"], P["fy"]))
    a("#: **Cargas en la cabeza del tubo** (compresión y momento alrededor del eje x):")
    a("N_c = %s 'carga axial de compresión [kN]" % num(P["N"]))
    a("M_x = %s 'momento alrededor de x [kN·m]" % num(P["M"]))
    a("")
    a("## 2 · El elemento de cáscara (ShellMITC4, hoja 72)")
    a("")
    a("#: Sección elástica membrana + placa de espesor t, con cortante transversal κ = 5/6:")
    a("#hide")
    a(funcs())
    a("function dd = seccion(E, nu, t)")
    a("  Mm = E/(1 - nu^2)·t")
    a("  G = 0.5·E/(1 + nu)·t")
    a("  Gs = G·(5/6)")
    a("  D = E·t^3/12/(1 - nu^2)")
    a("  dd = zeros(8, 8)")
    a("  dd(1, 1) = Mm")
    a("  dd(2, 2) = Mm")
    a("  dd(1, 2) = nu·Mm")
    a("  dd(2, 1) = nu·Mm")
    a("  dd(3, 3) = G")
    a("  dd(4, 4) = -D")
    a("  dd(5, 5) = -D")
    a("  dd(4, 5) = -nu·D")
    a("  dd(5, 4) = -nu·D")
    a("  dd(6, 6) = -0.5·D·(1 - nu)")
    a("  dd(7, 7) = Gs")
    a("  dd(8, 8) = Gs")
    a("end")
    a("#show")
    a("dd_p = seccion(E, ν, t_p) 'sección de la placa")
    a("dd_c = seccion(E, ν, t_c) 'sección de la pared del tubo")
    a("")
    a("## 3 · La malla")
    a("")
    a("#: **Placa:** 8 × 8 elementos (81 nudos, z = 0). **Tubo:** 16 tramos de perímetro por 5 filas (80 nudos más; los de la fila de abajo son los de la placa: ahí está la soldadura). Los nudos del perímetro del tubo caen en las líneas de la malla de la placa que pasan por su línea media.")
    a("n_x = 9 'líneas por lado de la placa")
    a("n_p = 81 'nudos de la placa")
    a("n_n = 161 'nudos totales")
    a("n_e = 144 'elementos: 64 de placa y 80 de tubo")
    a("#hide")
    a("Xn = zeros(n_n, 3)")
    a("for j = 1:n_x")
    a("  for i = 1:n_x")
    a("    q = (j - 1)·n_x + i")
    a("    Xn(q, 1) = xs(i)")
    a("    Xn(q, 2) = ys(j)")
    a("  end")
    a("end")
    a("#: Perímetro del tubo: lado inferior (+x), derecho (+y), superior (−x), izquierdo (−y). Índices de línea 3 … 7.")
    a("pi_x = [3, 4, 5, 6, 7, 7, 7, 7, 7, 6, 5, 4, 3, 3, 3, 3] 'índice de línea en x de cada punto del perímetro")
    a("pi_y = [3, 3, 3, 3, 3, 4, 5, 6, 7, 7, 7, 7, 7, 6, 5, 4] 'índice de línea en y")
    a("Pn = zeros(16, 1)")
    a("for k = 1:16")
    a("  Pn(k) = (pi_y(k) - 1)·n_x + pi_x(k)")
    a("end")
    a("for l = 1:n_z")
    a("  for k = 1:16")
    a("    q = n_p + (l - 1)·16 + k")
    a("    Xn(q, 1) = xs(pi_x(k))")
    a("    Xn(q, 2) = ys(pi_y(k))")
    a("    Xn(q, 3) = H_c·l/n_z")
    a("  end")
    a("end")
    a("En = zeros(n_e, 4)")
    a("for j = 1:8")
    a("  for i = 1:8")
    a("    e = (j - 1)·8 + i")
    a("    q = (j - 1)·n_x + i")
    a("    En(e, :) = [q, q + 1, q + n_x + 1, q + n_x]")
    a("  end")
    a("end")
    a("function q = nodo_tubo(l, k, Pn, n_p)")
    a("  if l == 0")
    a("    q = Pn(k)")
    a("  else")
    a("    q = n_p + (l - 1)·16 + k")
    a("  end")
    a("end")
    a("e = 64")
    a("for l = 1:n_z")
    a("  for k = 1:16")
    a("    k2 = mod(k, 16) + 1")
    a("    e = e + 1")
    a("    En(e, :) = [nodo_tubo(l - 1, k, Pn, n_p), nodo_tubo(l - 1, k2, Pn, n_p), nodo_tubo(l, k2, Pn, n_p), nodo_tubo(l, k, Pn, n_p)]")
    a("  end")
    a("end")
    a("#show")
    a("Xn_b = Xn(1:3, :) 'primeros nudos: z = 0, en la esquina de la placa")
    a("")
    a("## 4 · Ensamblaje de la rigidez")
    a("")
    a("#: Seis grados de libertad por nudo: u_x, u_y, u_z, θ_x, θ_y, θ_z (los del nudo q son 6(q − 1) + 1 … 6). Cada elemento suma su matriz de 24 × 24 en las filas y columnas de sus cuatro nudos; los nudos compartidos del borde del tubo son la **soldadura**.")
    a("n_g = 6·n_n 'grados de libertad")
    a("#hide")
    a("K = zeros(n_g, n_g)")
    a("function g = gdl(q)")
    a("  g = 6·(q - 1) + (1:6)")
    a("end")
    a("for e = 1:n_e")
    a("  q = En(e, :)")
    a("  Xe = [Xn(q(1), :); Xn(q(2), :); Xn(q(3), :); Xn(q(4), :)]")
    a("  if e <= 64")
    a("    Ke = mitc4_K(Xe, dd_p)")
    a("  else")
    a("    Ke = mitc4_K(Xe, dd_c)")
    a("  end")
    a("  g = [gdl(q(1)), gdl(q(2)), gdl(q(3)), gdl(q(4))]")
    a("  K(g, g) = K(g, g) + Ke")
    a("end")
    a("#show")
    a("")
    a("## 5 · Los apoyos: hormigón solo a compresión y pernos solo a tracción")
    a("")
    a("#: Cada nudo de la placa lleva un muelle vertical de rigidez k_c por su **área tributaria**. Los pernos están en los cuatro nudos de las líneas 2 y 8, con rigidez k_b. Para que el modelo no flote en el plano: se fijan u_x y u_y en el centro de la placa y u_y en el centro del borde x = + L_x.")
    a("#hide")
    a("kc_i = zeros(n_p, 1)")
    a("for j = 1:n_x")
    a("  for i = 1:n_x")
    a("    i0 = max(i - 1, 1)")
    a("    i1 = min(i + 1, n_x)")
    a("    j0 = max(j - 1, 1)")
    a("    j1 = min(j + 1, n_x)")
    a("    kc_i((j - 1)·n_x + i) = k_c·(xs(i1) - xs(i0))/2·(ys(j1) - ys(j0))/2")
    a("  end")
    a("end")
    a("kb_i = zeros(n_p, 1)")
    a("nb = [(2 - 1)·n_x + 2, (2 - 1)·n_x + 8, (8 - 1)·n_x + 2, (8 - 1)·n_x + 8]")
    a("for m = 1:4")
    a("  kb_i(nb(m)) = k_b")
    a("end")
    a("#show")
    a("#: Nudos de los pernos:")
    a("nb")
    a("")
    a("## 6 · Las cargas")
    a("")
    a("#: Se reparten en los 16 nudos de la cabeza del tubo con la distribución lineal de esfuerzos σ = −N/A − M·y/I de la sección (A = Σ a_k, I = Σ a_k·y_k², a_k = longitud tributaria × t_c): la resultante es exactamente N y M. La longitud tributaria de cada nudo es la mitad de los dos tramos que lo rodean.")
    a("#hide")
    a("ell = zeros(16, 1)")
    a("yk = zeros(16, 1)")
    a("for k = 1:16")
    a("  k0 = mod(k + 14, 16) + 1")
    a("  k2 = mod(k, 16) + 1")
    a("  d0 = sqrt((xs(pi_x(k)) - xs(pi_x(k0)))^2 + (ys(pi_y(k)) - ys(pi_y(k0)))^2)")
    a("  d2 = sqrt((xs(pi_x(k)) - xs(pi_x(k2)))^2 + (ys(pi_y(k)) - ys(pi_y(k2)))^2)")
    a("  ell(k) = (d0 + d2)/2")
    a("  yk(k) = ys(pi_y(k))")
    a("end")
    a("function Fc = carga(N, M, yk, ell, n_p, n_z, n_g, t_c)")
    a("  A_t = 0")
    a("  I_t = 0")
    a("  for k = 1:16")
    a("    A_t = A_t + ell(k)·t_c")
    a("    I_t = I_t + ell(k)·t_c·yk(k)^2")
    a("  end")
    a("  Fc = zeros(n_g, 1)")
    a("  for k = 1:16")
    a("    q = n_p + (n_z - 1)·16 + k")
    a("    Fc(6·(q - 1) + 3) = (-N/A_t - M·yk(k)/I_t)·ell(k)·t_c")
    a("  end")
    a("end")
    a("F = carga(N_c, M_x, yk, ell, n_p, n_z, n_g, t_c)")
    a("A_t = 0")
    a("I_t = 0")
    a("for k = 1:16")
    a("  A_t = A_t + ell(k)·t_c")
    a("  I_t = I_t + ell(k)·t_c·yk(k)^2")
    a("end")
    a("#show")
    a("A_t 'área de la sección del tubo [m2]")
    a("I_t 'inercia discreta del tubo [m4]")
    a("S_F = sum(F) 'resultante vertical de las cargas [kN] (debe ser −N)")
    a("")
    a("## 7 · Solución: conjunto activo de muelles")
    a("")
    a("#: Se resuelve con todos los muelles de hormigón activos y ningún perno; después se **apagan** los de hormigón que suben (u_z > 0) y se **encienden** los pernos que suben, y se repite hasta que el conjunto no cambia.")
    a("#hide")
    a("function Uc = resuelve(K, Fc, kc_i, kb_i, n_p, n_g)")
    a("  c_on = ones(n_p, 1)")
    a("  b_on = zeros(n_p, 1)")
    a("  cambia = 1")
    a("  iters = 0")
    a("  Uc = zeros(n_g, 1)")
    a("  while cambia > 0 && iters < 30")
    a("    Kt = K")
    a("    for q = 1:n_p")
    a("      d3 = 6·(q - 1) + 3")
    a("      Kt(d3, d3) = Kt(d3, d3) + c_on(q)·kc_i(q) + b_on(q)·kb_i(q)")
    a("    end")
    a("    for d = [6·(41 - 1) + 1, 6·(41 - 1) + 2, 6·(45 - 1) + 2]")
    a("      Kt(d, :) = 0")
    a("      Kt(:, d) = 0")
    a("      Kt(d, d) = 1")
    a("    end")
    a("    Ft = Fc")
    a("    for d = [6·(41 - 1) + 1, 6·(41 - 1) + 2, 6·(45 - 1) + 2]")
    a("      Ft(d) = 0")
    a("    end")
    a("    Uc = clsolve(Kt, Ft)")
    a("    cambia = 0")
    a("    for q = 1:n_p")
    a("      uz = Uc(6·(q - 1) + 3)")
    a("      if c_on(q) == 1 && uz > 0")
    a("        c_on(q) = 0")
    a("        cambia = cambia + 1")
    a("      end")
    a("      if c_on(q) == 0 && uz < 0")
    a("        c_on(q) = 1")
    a("        cambia = cambia + 1")
    a("      end")
    a("      if kb_i(q) > 0")
    a("        if b_on(q) == 0 && uz > 0")
    a("          b_on(q) = 1")
    a("          cambia = cambia + 1")
    a("        end")
    a("        if b_on(q) == 1 && uz < 0")
    a("          b_on(q) = 0")
    a("          cambia = cambia + 1")
    a("        end")
    a("      end")
    a("    end")
    a("    iters = iters + 1")
    a("  end")
    a("end")
    a("U = resuelve(K, F, kc_i, kb_i, n_p, n_g)")
    a("c_on = zeros(n_p, 1)")
    a("b_on = zeros(n_p, 1)")
    a("for q = 1:n_p")
    a("  if U(6·(q - 1) + 3) < 0")
    a("    c_on(q) = 1")
    a("  end")
    a("  if U(6·(q - 1) + 3) > 0 && kb_i(q) > 0")
    a("    b_on(q) = 1")
    a("  end")
    a("end")
    a("#show")
    a("")
    a("## 8 · Resultados")
    a("")
    a("#hide")
    a("Rc = zeros(n_p, 1)")
    a("Rb = zeros(n_p, 1)")
    a("uz_p = zeros(n_p, 1)")
    a("pres = zeros(n_p, 1)")
    a("for q = 1:n_p")
    a("  uz_p(q) = U(6·(q - 1) + 3)")
    a("  Rc(q) = -c_on(q)·kc_i(q)·uz_p(q)")
    a("  Rb(q) = -b_on(q)·kb_i(q)·uz_p(q)")
    a("  pres(q) = Rc(q)/(kc_i(q)/k_c)")
    a("end")
    a("#show")
    a("R_conc = sum(Rc) 'reacción total del hormigón (hacia arriba) [kN]")
    a("T_b = sum(Rb) 'fuerza total de los pernos (hacia abajo: negativa) [kN]")
    a("equil = R_conc + T_b + S_F 'equilibrio vertical: debe ser 0 [kN]")
    a("sig_max = max(pres)/1000 'presión máxima de contacto [MPa]")
    a("n_lev = n_p - sum(c_on) 'nudos de la placa levantados del hormigón")
    a("T_1 = -min(Rb) 'tracción del perno más cargado [kN]")
    a("#: **Pedestal.** Resistencia de contacto del hormigón f_cd = 25/1.5 y factor de confinamiento k_j = √(A_pedestal/A_placa) ≤ 3, con el pedestal de %.2f × %.2f m:" % P["ped"])
    a("f_cd = 25/1.5 'resistencia de cálculo del hormigón [MPa]")
    a("k_j = min(3, sqrt(%.4f/(%.4f·%.4f))) 'factor de confinamiento" % (pedA, Bl, Nl))
    a("rat_c = sig_max/(k_j·f_cd) 'aprovechamiento del contacto")
    a("#: **Perno.** Resistencia a tracción de un M24 de clase 8.8: 0.9·f_ub·A_s/γ_M2 con f_ub = 800 MPa y γ_M2 = 1.25:")
    a("F_tRd = 0.9·800000·A_b/1.25 'resistencia a tracción de un perno [kN]")
    a("rat_b = T_1/F_tRd 'aprovechamiento del perno")
    a("")
    a("## 9 · La soldadura tubo-placa")
    a("")
    a("#: Los elementos del tubo de la fila de abajo transmiten a la placa, por cada nudo del perímetro, tres fuerzas (axial y dos de corte). Dividida por la longitud tributaria da la **fuerza por unidad de longitud** de soldadura q_w. La garganta necesaria para una soldadura en ángulo exterior (EN 1993-1-8, método simplificado) es a = q_w / f_vw,d con f_vw,d = f_u/(√3·β_w·γ_M2), f_u = 510 MPa, β_w = 0.90 (S355), γ_M2 = 1.25:")
    a("#hide")
    a("Fw = zeros(16, 3)")
    a("for e = 65:80")
    a("  q = En(e, :)")
    a("  Xe = [Xn(q(1), :); Xn(q(2), :); Xn(q(3), :); Xn(q(4), :)]")
    a("  Ke = mitc4_K(Xe, dd_c)")
    a("  g = [gdl(q(1)), gdl(q(2)), gdl(q(3)), gdl(q(4))]")
    a("  ug = zeros(24, 1)")
    a("  for r = 1:24")
    a("    ug(r) = U(g(r))")
    a("  end")
    a("  fe = Ke·ug")
    a("  k1 = e - 64")
    a("  k2 = mod(k1, 16) + 1")
    a("  for c3 = 1:3")
    a("    Fw(k1, c3) = Fw(k1, c3) + fe(c3)")
    a("    Fw(k2, c3) = Fw(k2, c3) + fe(6 + c3)")
    a("  end")
    a("end")
    a("qw = zeros(16, 1)")
    a("for k = 1:16")
    a("  qw(k) = sqrt(Fw(k, 1)^2 + Fw(k, 2)^2 + Fw(k, 3)^2)/ell(k)")
    a("end")
    a("#show")
    a("S_wz = sum(Fw(:, 3)) 'suma de las fuerzas verticales que baja la soldadura a la placa [kN]")
    a("q_w = max(qw) 'fuerza máxima por unidad de longitud de soldadura [kN/m]")
    a("f_vwd = 510000/(sqrt(3)·0.9·1.25) 'resistencia de cálculo a cortante de la soldadura [kPa]")
    a("a_req = q_w/f_vwd·1000 'garganta necesaria [mm]")
    a("")
    a("## 10 · El método analítico de AISC (Guía de Diseño 1): la placa como voladizo")
    a("")
    a("#: **La idea.** AISC trata la placa como un **voladizo** que sale de la cara del tubo: la presión del hormigón (un bloque uniforme de resistencia f_p) la dobla hacia arriba; si el momento es grande, la placa se levanta de un lado y la **tracción de los pernos** la dobla hacia abajo. El espesor sale de pedir que el momento por unidad de ancho no pase de la resistencia plástica t²·F_y/4. Para una columna **hueca cuadrada o rectangular** la Guía de Diseño 1 mide los voladizos hasta 0.95 veces el lado del tubo: m = (N − 0.95·d)/2 en el plano del momento y n = (B − 0.95·b)/2 en el otro; manda el mayor.")
    a("#: **Datos del método** (LRFD): placa N × B = %.3f × %.3f m, tubo de %.3f × %.3f m (d × b), F_y = 355 MPa, f′_c = 25 MPa sobre un pedestal de %.2f × %.2f m, pernos a f = %.3f m del eje en el plano del momento:" % (Nl, Bl, P["dy"], P["bx"], P["ped"][0], P["ped"][1], P["fy"]))
    a("N_p = %s 'dimensión de la placa en el plano del momento [m]" % num(Nl))
    a("B_p = %s 'ancho de la placa [m]" % num(Bl))
    a("d_t = %s 'lado del tubo en el plano del momento [m]" % num(P["dy"]))
    a("b_t = %s 'lado del tubo en el otro sentido [m]" % num(P["bx"]))
    a("F_y = 355000 'límite elástico de la placa [kPa]")
    a("fc_p = 25000 'resistencia del hormigón f′_c [kPa]")
    a("A_ped = %s 'área del pedestal [m2]" % num(pedA))
    a("f_b = %s 'distancia del eje a los pernos, en el plano del momento [m]" % num(P["fy"]))
    a("#: **Resistencia de contacto** (φ_c = 0.65; el factor de confinamiento √(A₂/A₁) no pasa de 2):")
    a("f_pmax = 0.65·0.85·fc_p·min(2, sqrt(A_ped/(N_p·B_p))) 'presión máxima de contacto de cálculo [kPa]")
    a("q_max = f_pmax·B_p 'carga máxima por metro de la placa [kN/m]")
    a("m_c = (N_p - 0.95·d_t)/2 'voladizo en el plano del momento, hasta 0.95 del lado del tubo [m]")
    a("n_c = (B_p - 0.95·b_t)/2 'voladizo en el otro sentido [m]")
    a("u_t = f_b - 0.95·d_t/2 'del perno a la cara del tubo [m]")
    a("#hide")
    a("function R = aisc(P, M, N_p, B_p, f_b, f_pmax, q_max, m_c, u_t, F_y)")
    a("  e = M/P")
    a("  e_cr = N_p/2 - P/(2·q_max)")
    a("  if e <= e_cr")
    a("    Y = N_p - 2·e")
    a("    T = 0")
    a("    f_p = P/(Y·B_p)")
    a("  else")
    a("    Y = (f_b + N_p/2) - sqrt((f_b + N_p/2)^2 - 2·P·(e + f_b)/q_max)")
    a("    T = q_max·Y - P")
    a("    f_p = f_pmax")
    a("  end")
    a("  if Y >= m_c")
    a("    Mc = f_p·m_c^2/2")
    a("  else")
    a("    Mc = f_p·Y·(m_c - Y/2)")
    a("  end")
    a("  Mt = T·u_t/B_p")
    a("  t_r = sqrt(4·max(Mc, Mt)/(0.9·F_y))")
    a("  R = [e; e_cr; Y; T; f_p; Mc; Mt; t_r]")
    a("end")
    a("#show")
    a("A_r = aisc(N_c, M_x, N_p, B_p, f_b, f_pmax, q_max, m_c, u_t, F_y) 'e · e_crít · Y · T · f_p · M_contacto · M_perno · t_req")
    a("#: **Excentricidad.** e = M/P se compara con la crítica e_crít = N/2 − P/(2·q_max): por debajo, la placa solo comprime (longitud de apoyo Y = N − 2e, bloque uniforme f_p = P/(Y·B)); por encima, la placa se levanta, los pernos de ese lado trabajan con T = q_max·Y − P y Y sale de la ecuación de momentos respecto de los pernos.")
    a("e_a = A_r(1) 'excentricidad e = M/P [m]")
    a("e_crit = A_r(2) 'excentricidad crítica [m]")
    a("Y_a = A_r(3) 'longitud de apoyo [m]")
    a("T_a = A_r(4) 'tracción total de los pernos de un lado [kN]")
    a("t_a = A_r(8)·1000 'espesor de placa necesario por AISC [mm]")
    a("")
    a("## 11 · Lo mismo por elementos finitos, barriendo el momento")
    a("")
    a("#: Con el modelo por elementos finitos se repite el cálculo para momentos de 0 a %g kN·m con la misma carga axial. De cada solución se leen los **mismos números** que da AISC: la tracción de los pernos, el momento de voladizo por unidad de ancho en la cara del tubo (a partir de las reacciones del hormigón y de los pernos) y el espesor que resulta de él." % P["Mfin"])
    a("#hide")
    a("function R = post(Uc, kc_i, kb_i, ys, n_p, n_x, B_p, y_s)")
    a("  Rc_t = 0")
    a("  Tb = 0")
    a("  nl = 0")
    a("  Mp = 0")
    a("  Mn = 0")
    a("  for j = 1:n_x")
    a("    for i = 1:n_x")
    a("      q = (j - 1)·n_x + i")
    a("      uz = Uc(6·(q - 1) + 3)")
    a("      rc = 0")
    a("      rb = 0")
    a("      if uz < 0")
    a("        rc = -kc_i(q)·uz")
    a("      else")
    a("        nl = nl + 1")
    a("        if kb_i(q) > 0")
    a("          rb = kb_i(q)·uz")
    a("        end")
    a("      end")
    a("      Rc_t = Rc_t + rc")
    a("      Tb = Tb + rb")
    a("      if ys(j) > y_s + 1e-9")
    a("        Mp = Mp + (rc - rb)·(ys(j) - y_s)")
    a("      end")
    a("      if ys(j) < -y_s - 1e-9")
    a("        Mn = Mn + (rc - rb)·(-ys(j) - y_s)")
    a("      end")
    a("    end")
    a("  end")
    a("  R = [Rc_t; Tb; nl; abs(Mp)/B_p; abs(Mn)/B_p]")
    a("end")
    a("y_s = ys(7) 'cara del tubo (línea media), donde empieza el voladizo [m]")
    a("n_m = 10")
    a("ms = zeros(n_m, 1)")
    a("for s = 1:n_m")
    a("  ms(s) = (s - 1)·%s/9" % num(P["Mfin"]))
    a("end")
    a("Tm = zeros(n_m, 2)")
    a("Tr = zeros(n_m, 2)")
    a("Ym = zeros(n_m, 2)")
    a("TmA = zeros(n_m, 2)")
    a("for s = 1:n_m")
    a("  Fs = carga(N_c, ms(s), yk, ell, n_p, n_z, n_g, t_c)")
    a("  Us = resuelve(K, Fs, kc_i, kb_i, n_p, n_g)")
    a("  Ps = post(Us, kc_i, kb_i, ys, n_p, n_x, B_p, y_s)")
    a("  As = aisc(N_c, ms(s), N_p, B_p, f_b, f_pmax, q_max, m_c, u_t, F_y)")
    a("  Tm(s, 1) = ms(s)")
    a("  Tm(s, 2) = Ps(2)")
    a("  Tr(s, 1) = ms(s)")
    a("  Tr(s, 2) = 1000·sqrt(4·max(Ps(4), Ps(5))/(0.9·F_y))")
    a("  Ym(s, 1) = ms(s)")
    a("  Ym(s, 2) = 1000·As(8)")
    a("  TmA(s, 1) = ms(s)")
    a("  TmA(s, 2) = As(4)")
    a("end")
    a("#show")
    a("")
    a("#: **Gráfica 1. Tracción total de los pernos de un lado frente al momento** (N = %g kN). Los puntos azules son el cálculo por elementos finitos (placa elástica con muelles); los naranjas, el método de AISC (bloque rígido-plástico). AISC no da tracción hasta que e = M/P pasa de e_crít; por elementos finitos la placa se **flexiona** y los pernos empiezan a trabajar antes, porque la presión no es un bloque uniforme sino que crece hacia el borde comprimido." % P["N"])
    a("#fplot(FEM = Tm, AISC = TmA, [0 %g])" % P["Mfin"])
    a("#: **Gráfica 2. Espesor de placa necesario frente al momento** (mm). Azul: el que sale del momento de voladizo leído en el modelo de elementos finitos; naranja: AISC. La placa real es de %.0f mm." % (P["t_p"] * 1000))
    a("#fplot(FEM = Tr, AISC = Ym, [0 %g])" % P["Mfin"])
    a("")
    Mg = round(P["Mfin"] * 0.8)
    a("#: **Gráfica 3. La presión bajo la placa, a lo largo de su línea central, con M = %g kN·m.** Los puntos azules son la presión de contacto por elementos finitos (MPa); los naranjas, el bloque uniforme de AISC sobre la longitud de apoyo Y. El borde comprimido está en y = +%.3f m. Se ve la diferencia de fondo: AISC reparte la carga en un **bloque plano** y por eso necesita más espesor; por elementos finitos la presión **crece hacia el borde** y el momento de voladizo es menor." % (Mg, P["Ly"]))
    a("#hide")
    a("Ug = resuelve(K, carga(N_c, %g, yk, ell, n_p, n_z, n_g, t_c), kc_i, kb_i, n_p, n_g)" % Mg)
    a("Ag = aisc(N_c, %g, N_p, B_p, f_b, f_pmax, q_max, m_c, u_t, F_y)" % Mg)
    a("Pc = zeros(n_x, 2)")
    a("for j = 1:n_x")
    a("  q = (j - 1)·n_x + 5")
    a("  Pc(j, 1) = ys(j)")
    a("  Pc(j, 2) = max(0, -k_c·Ug(6·(q - 1) + 3))/1000")
    a("end")
    a("Pa = zeros(41, 2)")
    a("for s = 1:41")
    a("  yy = -%s + (s - 1)·%s/20" % (num(P["Ly"]), num(P["Ly"])))
    a("  Pa(s, 1) = yy")
    a("  if yy >= %s - Ag(3) - 1e-9" % num(P["Ly"]))
    a("    Pa(s, 2) = Ag(5)/1000")
    a("  end")
    a("end")
    a("#show")
    a("Y_g = Ag(3) 'longitud de apoyo de AISC con ese momento [m]")
    a("T_g = Ag(4) 'tracción de AISC con ese momento [kN]")
    a("#fplot(FEM = Pc, AISC = Pa, [-%s %s])" % (num(P["Ly"]), num(P["Ly"])))
    a("")
    a("## 12 · Comparación para el caso de la hoja (N = %g kN, M = %g kN·m)" % (P["N"], P["M"]))
    a("")
    a("#hide")
    a("Pf = post(U, kc_i, kb_i, ys, n_p, n_x, B_p, y_s)")
    a("#show")
    a("T_fem = Pf(2) 'tracción total de los pernos (FEM) [kN]")
    a("M_fem = max(Pf(4), Pf(5)) 'momento de voladizo por unidad de ancho (FEM) [kN·m/m]")
    a("t_fem = 1000·sqrt(4·M_fem/(0.9·F_y)) 'espesor necesario (FEM) [mm]")
    a("M_aisc = max(A_r(6), A_r(7)) 'momento de voladizo por unidad de ancho (AISC) [kN·m/m]")
    a("#: **Qué dice cada método.** AISC: bloque uniforme de presión sobre la longitud de apoyo Y y, si e > e_crít, tracción en los pernos. Elementos finitos: la placa se deforma, la presión es lineal y los pernos se activan a medida que la placa los levanta. Los dos dan el espesor con la misma regla (voladizo plástico t² F_y/4 = M).")
    c = COMP[clave]
    a("#: **Comparación con otros dos programas** (mismo modelo: mismos 161 nudos, mismas cargas, hormigón solo a compresión y pernos solo a tracción). **Abaqus**: cáscara S4 y muelles no lineales, corrido por línea de órdenes. **IDEA StatiCa**: su solver de elementos finitos CBFEM (k2fem64, cáscara CQUAD4 y contacto con elementos gap), corrido sin conexión y sin su programa; **no es el modelo propio de IDEA de la conexión**, es su solver con este mismo modelo. La columna de la hoja es el cálculo de arriba; las otras dos se dan como referencia, no se usan en el cálculo.")
    a("#: - **Tracción total de los pernos** (kN): hoja %s · Abaqus %s · IDEA %s · AISC 0 (supone la placa rígida y sin despegue: e < e_crít)" % c["T"])
    a("#: - **Reacción total del hormigón** (kN): hoja %s · Abaqus %s · IDEA %s" % c["R"])
    a("#: - **Flecha máxima hacia arriba de la placa** (mm): hoja %s · Abaqus %s · IDEA %s" % c["up"])
    a("#: - **Flecha máxima hacia abajo de la placa** (mm): hoja %s · Abaqus %s · IDEA %s" % c["dn"])
    a("#: - **Elevación del perno más cargado** (mm): hoja %s · Abaqus %s · IDEA %s" % c["pb"])
    a("#: - **Equilibrio vertical** (suma de reacciones, con N = 300 kN): hoja 300.000 · Abaqus 300.000 · IDEA 300.0006")
    a("#: - **Tensión de Von Mises máxima en la placa** (MPa): hoja %s · Abaqus %s" % c["vm"])
    a("#: - **Fuerza de soldadura máxima por nudo** (kN): hoja %s · Abaqus %s" % c["sw"])
    a("#: Los tres modelos de elementos finitos coinciden dentro de 1 % en las fuerzas (pernos, hormigón, soldadura) y de 3 % en la flecha máxima; las diferencias salen de la formulación de la cáscara de cada programa. **AISC es de otra familia**: sin despegue de la placa no hay tracción en los pernos y el momento de voladizo es el de la sección 16 (M_aisc), más del doble del que da la cáscara.")
    a("")
    a("## 13 · La unión dibujada")
    a("")
    a("#: **Sección acotada** por el plano del momento: la placa sobre el pedestal, el tubo hueco y los pernos. m es el voladizo de la placa hasta 0.95 del lado del tubo; u, la distancia del perno a esa cara.")
    Ly, dy, fy_, tp = P["Ly"], P["dy"], P["fy"], P["t_p"]
    hp = 0.40
    a('#dibujo("Placa base de columna tubular: sección por el plano del momento", ud = m, escala = auto, cotas = m, ancho = 190, alto = 150)')
    a('#  rect(%s, %s, %s, %s, "gruesa")' % (num(-P["ped"][1] / 2), num(-hp), num(P["ped"][1]), num(hp)))
    a('#  rect(%s, 0, %s, t_p, "gruesa")' % (num(-Ly), num(2 * Ly)))
    a('#  achurado(%s, 0, %s, t_p, "acero")' % (num(-Ly), num(2 * Ly)))
    a('#  poligono(%s, t_p, %s, t_p, %s, 0.30, %s, 0.30, "gruesa")' % (num(-dy / 2), num(-dy / 2 + P["t_c"]), num(-dy / 2 + P["t_c"]), num(-dy / 2)))
    a('#  poligono(%s, t_p, %s, t_p, %s, 0.30, %s, 0.30, "gruesa")' % (num(dy / 2 - P["t_c"]), num(dy / 2), num(dy / 2), num(dy / 2 - P["t_c"])))
    a('#  linea(%s, %s, %s, 0.055, "gruesa verde")' % (num(-fy_), num(-hp + 0.12), num(-fy_)))
    a('#  linea(%s, %s, %s, 0.055, "gruesa verde")' % (num(fy_), num(-hp + 0.12), num(fy_)))
    a('#  texto(0.0, 0.34, "tubo hueco %s", 3, "c")' % nom)
    a('#  texto(0.0, %s, "pedestal de hormigón %.2f × %.2f m", 3, "c")' % (num(-hp - 0.06), P["ped"][0], P["ped"][1]))
    a('#  texto(%s, %s, "perno M24", 2.6, "i", estilo = "verde")' % (num(fy_ + 0.03), num(-0.10)))
    a('#  flecha(0.0, 0.52, 0.0, 0.32, "rojo")')
    a('#  texto(0.02, 0.50, "N = %g kN · M = %g kN·m", 2.6, "i", estilo = "rojo")' % (P["N"], P["M"]))
    a('#  cota(%s, %s, %s, %s, -0.04, "%.3f")' % (num(-Ly), num(-hp - 0.12), num(Ly), num(-hp - 0.12), 2 * Ly))
    a('#  cota(%s, 0.06, %s, 0.06, 0.03, "m = %.3f")' % (num(0.95 * dy / 2), num(Ly), m_c))
    a('#  cota(%s, %s, %s, %s, -0.03, "u = %.3f")' % (num(0.95 * dy / 2), num(-0.22), num(fy_), num(-0.22), u_t))
    a('#  cota(0.0, -0.14, %s, -0.14, -0.03, "f = %.3f")' % (num(fy_), fy_))
    a('#  cota(%s, 0, %s, t_p, 0.03, "%.0f mm")' % (num(Ly + 0.04), num(Ly + 0.04), tp * 1000))
    a("#fin")
    a("")
    a("#: **Planta acotada**: la placa, el tubo, los cuatro pernos y la malla de la placa (la fila de nudos del borde del tubo es la soldadura).")
    a('#dibujo("Planta de la placa base: tubo, pernos y malla de elementos finitos", ud = m, escala = auto, cotas = m, ancho = 150, alto = 170)')
    a('#  rect(%s, %s, %s, %s, "gruesa")' % (num(-P["Lx"]), num(-Ly), num(2 * P["Lx"]), num(2 * Ly)))
    a('#  rect(%s, %s, %s, %s, "media rojo")' % (num(-P["bx"] / 2), num(-dy / 2), num(P["bx"]), num(dy)))
    a('#  rect(%s, %s, %s, %s, "media rojo")' % (num(-P["bx"] / 2 + P["t_c"]), num(-dy / 2 + P["t_c"]), num(P["bx"] - 2 * P["t_c"]), num(dy - 2 * P["t_c"])))
    for sx in (-1, 1):
        for sy in (-1, 1):
            a('#  circulo(%s, %s, 0.012, "gruesa verde")' % (num(sx * P["fx"]), num(sy * P["fy"])))
    for xv in P["xs"]:
        a('#  linea(%s, %s, %s, %s, "fina gris")' % (num(xv), num(-Ly), num(xv), num(Ly)))
    for yv in P["ys"]:
        a('#  linea(%s, %s, %s, %s, "fina gris")' % (num(-P["Lx"]), num(yv), num(P["Lx"]), num(yv)))
    a('#  texto(0.0, 0.0, "tubo", 2.6, "c", estilo = "rojo")')
    a('#  texto(%s, %s, "pernos M24", 2.6, "c", estilo = "verde")' % (num(P["fx"] + 0.005), num(P["fy"] + 0.025)))
    a('#  texto(%s, %s, "borde comprimido (+y)", 2.6, "c")' % (num(0.0), num(Ly + 0.045)))
    a('#  cota(%s, %s, %s, %s, -0.04, "%.3f")' % (num(-P["Lx"]), num(-Ly - 0.05), num(P["Lx"]), num(-Ly - 0.05), 2 * P["Lx"]))
    a('#  cota(%s, %s, %s, %s, 0.04, "%.3f")' % (num(P["Lx"] + 0.05), num(-Ly), num(P["Lx"] + 0.05), num(Ly), 2 * Ly))
    a('#  cota(%s, %s, %s, %s, -0.03, "%.3f")' % (num(-P["bx"] / 2), num(-dy / 2 - 0.015), num(P["bx"] / 2), num(-dy / 2 - 0.015), P["bx"]))
    a("#fin")
    a("")
    a("## 14 · La presión y la deformada de la placa")
    a("")
    a("#: **Mapa de presión de contacto** (kPa) en la planta de la placa, con el caso de la hoja: el hormigón trabaja solo en el lado comprimido (y positivo); la zona en cero es la que se despega. Con el cursor se lee el valor.")
    a("#hide")
    a("P_m = zeros(n_x, n_x)")
    a("for j = 1:n_x")
    a("  for i = 1:n_x")
    a("    P_m(i, j) = pres((j - 1)·n_x + i)")
    a("  end")
    a("end")
    a("n_f = 21")
    a("P_f = zeros(n_f, n_f)")
    a("for jf = 1:n_f")
    a("  for if_ = 1:n_f")
    a("    xq = -%s + (if_ - 1)·%s/10" % (num(P["Lx"]), num(P["Lx"])))
    a("    yq = -%s + (jf - 1)·%s/10" % (num(Ly), num(Ly)))
    a("    i0 = 1")
    a("    for i = 1:n_x - 1")
    a("      if xs(i) <= xq + 1e-9")
    a("        i0 = i")
    a("      end")
    a("    end")
    a("    j0 = 1")
    a("    for j = 1:n_x - 1")
    a("      if ys(j) <= yq + 1e-9")
    a("        j0 = j")
    a("      end")
    a("    end")
    a("    tx = (xq - xs(i0))/(xs(i0 + 1) - xs(i0))")
    a("    ty = (yq - ys(j0))/(ys(j0 + 1) - ys(j0))")
    a("    P_f(if_, jf) = (1 - tx)·(1 - ty)·P_m(i0, j0) + tx·(1 - ty)·P_m(i0 + 1, j0) + (1 - tx)·ty·P_m(i0, j0 + 1) + tx·ty·P_m(i0 + 1, j0 + 1)")
    a("  end")
    a("end")
    a("#show")
    a("p_xy(x, y) = spline(1 + (x + %s)/(%s/10), 1 + (y + %s)/(%s/10), P_f)" % (num(P["Lx"]), num(P["Lx"]), num(Ly), num(Ly)))
    a("#map(p_xy(x, y), [-%s %s], [-%s %s])" % (num(P["Lx"]), num(P["Lx"]), num(Ly), num(Ly)))
    a("#: **Tensión de la placa.** Con los giros de cada elemento se calculan las curvaturas en su centro (κ₁₁ = −∂θ_y/∂x, κ₂₂ = ∂θ_x/∂y, κ₁₂ = ∂θ_x/∂x − ∂θ_y/∂y), los momentos por unidad de ancho m = D·[κ₁₁ + νκ₂₂, νκ₁₁ + κ₂₂, (1 − ν)/2·κ₁₂] con D = E·t³/(12·(1 − ν²)), y las tensiones de la fibra extrema σ = 6·m/t². Se muestra la tensión equivalente de Von Mises (en MPa) promediada en los nudos de la placa:")
    a("#hide")
    a("sv_n = zeros(n_p, 1)")
    a("cn_n = zeros(n_p, 1)")
    a("D_p = E·t_p^3/12/(1 - ν^2)")
    a("sig_el = zeros(64, 1)")
    a("for e = 1:64")
    a("  q = En(e, :)")
    a("  dxi = [-0.25, 0.25, 0.25, -0.25]")
    a("  det_ = [-0.25, -0.25, 0.25, 0.25]")
    a("  j11 = 0")
    a("  j12 = 0")
    a("  j21 = 0")
    a("  j22 = 0")
    a("  for r = 1:4")
    a("    j11 = j11 + dxi(r)·Xn(q(r), 1)")
    a("    j12 = j12 + dxi(r)·Xn(q(r), 2)")
    a("    j21 = j21 + det_(r)·Xn(q(r), 1)")
    a("    j22 = j22 + det_(r)·Xn(q(r), 2)")
    a("  end")
    a("  dj = j11·j22 - j12·j21")
    a("  k11 = 0")
    a("  k22 = 0")
    a("  k12 = 0")
    a("  for r = 1:4")
    a("    dnx = (j22·dxi(r) - j12·det_(r))/dj")
    a("    dny = (-j21·dxi(r) + j11·det_(r))/dj")
    a("    tx = U(6·(q(r) - 1) + 4)")
    a("    ty = U(6·(q(r) - 1) + 5)")
    a("    k11 = k11 - dnx·ty")
    a("    k22 = k22 + dny·tx")
    a("    k12 = k12 + dnx·tx - dny·ty")
    a("  end")
    a("  m11 = D_p·(k11 + ν·k22)")
    a("  m22 = D_p·(ν·k11 + k22)")
    a("  m12 = D_p·(1 - ν)/2·k12")
    a("  sx = 6·m11/t_p^2")
    a("  sy = 6·m22/t_p^2")
    a("  txy = 6·m12/t_p^2")
    a("  svm = sqrt(sx^2 - sx·sy + sy^2 + 3·txy^2)/1000")
    a("  sig_el(e) = svm")
    a("  for r = 1:4")
    a("    sv_n(q(r)) = sv_n(q(r)) + svm")
    a("    cn_n(q(r)) = cn_n(q(r)) + 1")
    a("  end")
    a("end")
    a("S_m = zeros(n_x, n_x)")
    a("W_m = zeros(n_x, n_x)")
    a("for j = 1:n_x")
    a("  for i = 1:n_x")
    a("    q = (j - 1)·n_x + i")
    a("    sv_n(q) = sv_n(q)/cn_n(q)")
    a("    S_m(i, j) = sv_n(q)")
    a("    W_m(i, j) = 1000·U(6·(q - 1) + 3)")
    a("  end")
    a("end")
    a("S_f = zeros(n_f, n_f)")
    a("W_f = zeros(n_f, n_f)")
    a("for jf = 1:n_f")
    a("  for if_ = 1:n_f")
    a("    xq = -%s + (if_ - 1)·%s/10" % (num(P["Lx"]), num(P["Lx"])))
    a("    yq = -%s + (jf - 1)·%s/10" % (num(Ly), num(Ly)))
    a("    i0 = 1")
    a("    for i = 1:n_x - 1")
    a("      if xs(i) <= xq + 1e-9")
    a("        i0 = i")
    a("      end")
    a("    end")
    a("    j0 = 1")
    a("    for j = 1:n_x - 1")
    a("      if ys(j) <= yq + 1e-9")
    a("        j0 = j")
    a("      end")
    a("    end")
    a("    tx = (xq - xs(i0))/(xs(i0 + 1) - xs(i0))")
    a("    ty = (yq - ys(j0))/(ys(j0 + 1) - ys(j0))")
    a("    S_f(if_, jf) = (1 - tx)·(1 - ty)·S_m(i0, j0) + tx·(1 - ty)·S_m(i0 + 1, j0) + (1 - tx)·ty·S_m(i0, j0 + 1) + tx·ty·S_m(i0 + 1, j0 + 1)")
    a("    W_f(if_, jf) = (1 - tx)·(1 - ty)·W_m(i0, j0) + tx·(1 - ty)·W_m(i0 + 1, j0) + (1 - tx)·ty·W_m(i0, j0 + 1) + tx·ty·W_m(i0 + 1, j0 + 1)")
    a("  end")
    a("end")
    a("#show")
    a("sig_max_p = max(sv_n) 'tensión de Von Mises máxima en la placa (promedio de nudos) [MPa]")
    a("sig_el_max = max(sig_el) 'tensión de Von Mises máxima en el centro de un elemento [MPa]")
    a("rat_f = sig_el_max/355 'aprovechamiento de la placa frente al límite elástico de 355 MPa")
    a("s_xy(x, y) = spline(1 + (x + %s)/(%s/10), 1 + (y + %s)/(%s/10), S_f)" % (num(P["Lx"]), num(P["Lx"]), num(Ly), num(Ly)))
    a("#map(s_xy(x, y), [-%s %s], [-%s %s])" % (num(P["Lx"]), num(P["Lx"]), num(Ly), num(Ly)))
    a("#: **Desplazamiento vertical de la placa** (mm; positivo hacia arriba): la zona levantada es la del lado de los pernos traccionados.")
    a("w_xy(x, y) = spline(1 + (x + %s)/(%s/10), 1 + (y + %s)/(%s/10), W_f)" % (num(P["Lx"]), num(P["Lx"]), num(Ly), num(Ly)))
    a("#map(w_xy(x, y), [-%s %s], [-%s %s])" % (num(P["Lx"]), num(P["Lx"]), num(Ly), num(Ly)))
    a("#: **La deformada de la placa** (ampliada) con el hormigón en el lado comprimido y la placa levantada en el otro; con el ratón se gira y, al pasar el cursor, se lee el desplazamiento (mm) de cada nudo:")
    a("#hide")
    a("X_d = zeros(n_p, 3)")
    a("U_3 = zeros(n_p, 3)")
    a("w_j = zeros(n_p, 1)")
    a("for q = 1:n_p")
    a("  X_d(q, 1) = Xn(q, 1)")
    a("  X_d(q, 2) = Xn(q, 2)")
    a("  U_3(q, 3) = U(6·(q - 1) + 3)")
    a("  w_j(q) = 1000·U(6·(q - 1) + 3)")
    a("end")
    a("e_j = En(1:64, :)")
    a("e_f = zeros(0, 2)")
    a("v_f = zeros(0, 2)")
    a("#show")
    a("#modelo3d(X_d, e_j, e_f, w_j, v_f, U_3, 500)")
    a("#: **La misma deformada con la tensión de Von Mises** (MPa) de cada nudo al pasar el cursor:")
    a("#modelo3d(X_d, e_j, e_f, sv_n, v_f, U_3, 500)")
    a("")
    a("## 15 · Resumen")
    a("")
    a(("#: Con N = %g kN y M = %g kN·m (excentricidad %.3f m, mayor que N/6 = %.3f m de la placa): la placa **se despega** por el lado traccionado, los pernos de ese lado trabajan, y el hormigón del lado comprimido soporta la carga concentrada. Por elementos finitos hacen falta menos milímetros de placa que por AISC, porque AISC supone un bloque plano de presión; AISC es más conservador." % (P["N"], P["M"], P["M"] / P["N"], Nl / 6)))
    a("")
    a("## 16 · Del símbolo al número: la franja de placa como viga de elementos finitos")
    a("")
    a("#: **Qué es.** El método de AISC trata el voladizo de la placa como una **viga empotrada en la cara del tubo** con la presión del hormigón como carga. Aquí esa viga se resuelve **por elementos finitos**: primero **todo en símbolos** (el motor deduce las funciones de forma, la curvatura, la rigidez y la solución, sin ningún dato de la placa) y después **con los números** de esta hoja, con gráficas. Es la reducción a una dimensión de la cáscara de las secciones 2 a 8; la cáscara en sí ya se calculó con números.")
    a("")
    a("### 16.1 · En símbolos: el elemento empotrado-libre")
    a("#: El elemento mide L. Se mide x desde el empotramiento y se normaliza (de 0 a 1). Como en el empotramiento la flecha y el giro valen cero, la flecha es la suma de dos potencias, x² y x³. Sus dos coeficientes salen de las dos condiciones del extremo libre: flecha w y giro θ (la fila del giro va dividida por L):")
    a("A_c = Simplify{[1, 1; 2/L, 3/L]}")
    a("#: La inversa son los coeficientes de las dos funciones de forma (cada columna es una función):")
    a("C_c = Simplify{inv(A_c)}")
    a("#: Las funciones de forma (flecha por cada unidad de w y de θ en el extremo libre):")
    a("Phi_c = Simplify{[x^2, x^3]*C_c}")
    a("#: La curvatura es la segunda derivada de la flecha (el motor deriva cada potencia dos veces; el 1/L² pasa de x normalizada a x real):")
    a("d2p_c = [Partial{Partial{x^2 @ x} @ x}, Partial{Partial{x^3 @ x} @ x}]")
    a("B_c = Simplify{d2p_c*C_c*(1/L^2)}")
    a("#: **La rigidez** es la energía de flexión: K = EI·∫ Bᵀ·B dx sobre la longitud L. El motor integra con L y EI como letras:")
    a("K_c = Simplify{EI*L*Integral{transpose(B_c)*B_c @ x = 0 : 1}}")
    a("#: **La carga.** Una presión uniforme q (carga por metro de ancho) se reparte a los nudos con las mismas funciones de forma, F = q·L·∫ Φᵀ dx:")
    a("F_c = Simplify{q*L*Integral{transpose(Phi_c) @ x = 0 : 1}}")
    a("#: **La solución.** Se resuelve K·u = F, también en símbolos. Salen la flecha y el giro del borde libre de la placa, fórmulas exactas de un voladizo con carga uniforme:")
    a("u_c = Simplify{inv(K_c)*F_c}")
    a("#: **El momento en el empotramiento** (la cara del tubo) sale del equilibrio, M = q·L²/2. Es la fórmula de AISC, M_c = f_p·m²/2: el elemento finito la reproduce exactamente.")
    a("M_c_s = Simplify{q*L^2/2}")
    a("")
    a("### 16.2 · Con los números de la hoja")
    a("#: La presión de contacto es la del método de AISC de la sección 10 (bloque uniforme f_p) y el voladizo es m. Se arma la viga con n elementos iguales: la rigidez del elemento es la deducida arriba, EI/L³·[12, 6L, −12, 6L; …], con L la longitud de cada elemento.")
    a("EI_p = E·t_p^3/(12·(1 - ν^2)) 'rigidez a flexión de la placa por metro de ancho [kN·m]")
    a("q_s = A_r(5) 'presión de contacto por metro de ancho [kN/m]")
    a("L_v = m_c 'voladizo desde la cara del tubo [m]")
    a("#hide")
    a("function R = franja(n, Lv, EI, q)")
    a("  Le = Lv/n")
    a("  nd = 2·(n + 1)")
    a("  Ke = EI/Le^3·[12, 6·Le, -12, 6·Le; 6·Le, 4·Le^2, -6·Le, 2·Le^2; -12, -6·Le, 12, -6·Le; 6·Le, 2·Le^2, -6·Le, 4·Le^2]")
    a("  Fe = q·Le·[0.5; Le/12; 0.5; -Le/12]")
    a("  K0 = zeros(nd, nd)")
    a("  F0 = zeros(nd, 1)")
    a("  for e = 1:n")
    a("    for i = 1:4")
    a("      F0(2·(e - 1) + i) = F0(2·(e - 1) + i) + Fe(i)")
    a("      for j = 1:4")
    a("        K0(2·(e - 1) + i, 2·(e - 1) + j) = K0(2·(e - 1) + i, 2·(e - 1) + j) + Ke(i, j)")
    a("      end")
    a("    end")
    a("  end")
    a("  Kb = K0")
    a("  Fb = F0")
    a("  for i = 1:2")
    a("    for j = 1:nd")
    a("      Kb(i, j) = 0")
    a("      Kb(j, i) = 0")
    a("    end")
    a("    Kb(i, i) = 1")
    a("    Fb(i) = 0")
    a("  end")
    a("  Ug = clsolve(Kb, Fb)")
    a("  R = zeros(n + 1, 3)")
    a("  Re = K0·Ug - F0")
    a("  for k = 1:n + 1")
    a("    R(k, 1) = (k - 1)·Le")
    a("    R(k, 2) = Ug(2·k - 1)")
    a("  end")
    a("  R(1, 3) = abs(Re(2))")
    a("  for e = 1:n")
    a("    ue = zeros(4, 1)")
    a("    for i = 1:4")
    a("      ue(i) = Ug(2·(e - 1) + i)")
    a("    end")
    a("    me = Ke·ue - Fe")
    a("    R(e + 1, 3) = abs(me(4))")
    a("  end")
    a("end")
    a("w_ex = zeros(21, 2)")
    a("m_ex = zeros(21, 2)")
    a("for s = 1:21")
    a("  xx = (s - 1)·L_v/20")
    a("  w_ex(s, 1) = xx")
    a("  w_ex(s, 2) = 1000·q_s·xx^2·(6·L_v^2 - 4·L_v·xx + xx^2)/(24·EI_p)")
    a("  m_ex(s, 1) = xx")
    a("  m_ex(s, 2) = q_s·(L_v - xx)^2/2")
    a("end")
    a("F_4 = franja(4, L_v, EI_p, q_s)")
    a("W_4 = zeros(5, 2)")
    a("M_4 = zeros(5, 2)")
    a("for k = 1:5")
    a("  W_4(k, 1) = F_4(k, 1)")
    a("  W_4(k, 2) = 1000·F_4(k, 2)")
    a("  M_4(k, 1) = F_4(k, 1)")
    a("  M_4(k, 2) = F_4(k, 3)")
    a("end")
    a("Mr_n = zeros(4, 1)")
    a("nn_v = [1, 2, 4, 8]")
    a("for k = 1:4")
    a("  Rk = franja(nn_v(k), L_v, EI_p, q_s)")
    a("  Mr_n(k) = Rk(1, 3)")
    a("end")
    a("#show")
    a("M_exacto = q_s·L_v^2/2 'momento en la cara del tubo, fórmula de AISC [kN·m/m]")
    a("w_exacto = 1000·q_s·L_v^4/(8·EI_p) 'flecha del borde libre, fórmula simbólica [mm]")
    a("w_fe = W_4(5, 2) 'flecha del borde libre por elementos finitos, 4 elementos [mm]")
    a("M_fe_1 = Mr_n(1) 'momento en la cara del tubo con 1 elemento [kN·m/m]")
    a("M_fe_4 = Mr_n(3) 'con 4 elementos [kN·m/m]")
    a("M_fe_8 = Mr_n(4) 'con 8 elementos [kN·m/m]")
    a("#: **Gráfica 4. La flecha del voladizo de la placa** (mm; x desde la cara del tubo). Puntos naranjas: los 5 nudos de la viga de elementos finitos (4 elementos); azules: la fórmula exacta. Pasa el cursor sobre la gráfica para leer x y la flecha.")
    a("#fplot(Exacta = w_ex, FEM = W_4, [0 %s])" % num(m_c))
    a("#: **Gráfica 5. El momento flector** (kN·m por metro de ancho) en cada nudo. Puntos naranjas: elementos finitos (momento de extremo de elemento); azules: q·(L − x)²/2. En x = 0 está el momento de AISC.")
    a("#fplot(Exacta = m_ex, FEM = M_4, [0 %s])" % num(m_c))
    a("#: **Qué dice la comparación.** La viga de elementos finitos da en la cara del tubo **{M_exacto} kN·m/m**, el mismo momento de AISC (sección 10), con 1, 2, 4 u 8 elementos: la cúbica de Hermite es exacta para carga uniforme. En cambio la cáscara de las secciones 2 a 8 da M_fem de la sección 12, bastante menor: la presión real bajo la placa **no es uniforme** (es más baja junto al tubo, que rigidiza la placa) y la placa apoya también sobre las paredes del tubo; por eso AISC es conservador. La diferencia es de modelo, no de cálculo.")
    a("")
    a("#: Los 966 desplazamientos y giros (u_x, u_y, u_z, θ_x, θ_y, θ_z de cada nudo, en m y rad) para compararlos con Abaqus:")
    a("U_f = U 'desplazamientos y giros de los 161 nudos")
    a("sig_el_f = sig_el 'tensión de Von Mises en el centro de cada elemento de la placa [MPa]")
    a("Fw_f = Fw 'fuerzas de soldadura en los 16 nudos del perímetro: Fx, Fy, Fz [kN]")
    ruta = os.path.join(EJ, "%d %s.lisp" % (C["num"], C["titulo"]))
    open(ruta, "w", encoding="utf8", newline="\n").write("\n".join(H) + "\n")
    print("hoja escrita:", os.path.basename(ruta))


if __name__ == "__main__":
    for k in CASOS:
        hoja(k)
