# Sólidos y superficies como AutoCAD (AutoLISP)
#: Los comandos 3D de AutoCAD —**BOX, CYLINDER, SPHERE, EXTRUDE, REVOLVE** y las **superficies** z = f(x, y)— escritos como funciones de AutoLISP. Cada uno arma el sólido con caras 3DFACE (una malla cerrada), en su capa y con su color, y devuelve cuántas caras dibujó.
#: **Límite honesto:** un 3DSOLID verdadero de AutoCAD guarda un modelo ACIS propietario; aquí el sólido es una **malla de caras**, que se ve, se gira y se exporta a DXF y DWG, pero en AutoCAD se abre como caras y no como sólido editable.

#autolisp("Escena: caja, cilindro, esfera, losa en L, jarrón y cúpula", ancho = 200, alto = 130, exporta = nCaja nCil nEsf nExt nRev nSup nTotal)
;;; ---------- una cara (triángulo si c = d) ----------
(defun cara (a b c d lay col)
  (entmake (list '(0 . "3DFACE") (cons 8 lay) (cons 62 col) (cons 10 a) (cons 11 b) (cons 12 c) (cons 13 d))))
(defun p+ (p dx dy dz) (list (+ (car p) dx) (+ (cadr p) dy) (+ (caddr p) dz)))
;;; ---------- BOX: esquina p y tres lados ----------
(defun solid-box (p dx dy dz lay col / a b c d e f g h)
  (setq a p b (p+ p dx 0 0) c (p+ p dx dy 0) d (p+ p 0 dy 0))
  (setq e (p+ a 0 0 dz) f (p+ b 0 0 dz) g (p+ c 0 0 dz) h (p+ d 0 0 dz))
  (cara a d c b lay col) (cara e f g h lay col) (cara a b f e lay col)
  (cara b c g f lay col) (cara c d h g lay col) (cara d a e h lay col)
  6)
;;; ---------- CYLINDER: centro de la base, radio, altura, n lados ----------
(defun solid-cylinder (c r hh n lay col / i a0 a1 p0 p1 q0 q1 top n2)
  (setq i 0 top (p+ c 0 0 hh))
  (while (< i n)
    (setq a0 (* 2 pi (/ i (float n))) a1 (* 2 pi (/ (+ i 1) (float n))))
    (setq p0 (p+ c (* r (cos a0)) (* r (sin a0)) 0) p1 (p+ c (* r (cos a1)) (* r (sin a1)) 0))
    (setq q0 (p+ p0 0 0 hh) q1 (p+ p1 0 0 hh))
    (cara p0 p1 q1 q0 lay col)
    (cara c p1 p0 p0 lay col)
    (cara top q0 q1 q1 lay col)
    (setq i (+ i 1)))
  (* 3 n))
;;; ---------- SPHERE: centro, radio, meridianos y paralelos ----------
(defun esf-pt (c r th ph) (p+ c (* r (cos ph) (cos th)) (* r (cos ph) (sin th)) (* r (sin ph))))
(defun solid-sphere (c r nu nv lay col / i j th0 th1 ph0 ph1)
  (setq j 0)
  (while (< j nv)
    (setq ph0 (- (* pi (/ j (float nv))) (/ pi 2)) ph1 (- (* pi (/ (+ j 1) (float nv))) (/ pi 2)))
    (setq i 0)
    (while (< i nu)
      (setq th0 (* 2 pi (/ i (float nu))) th1 (* 2 pi (/ (+ i 1) (float nu))))
      (cara (esf-pt c r th0 ph0) (esf-pt c r th1 ph0) (esf-pt c r th1 ph1) (esf-pt c r th0 ph1) lay col)
      (setq i (+ i 1)))
    (setq j (+ j 1)))
  (* nu nv))
;;; ---------- EXTRUDE: contorno (lista de puntos en el plano z0) y altura ----------
;;; Las tapas se triangulan por «orejas» (ear clipping): sirve para cualquier polígono simple, también cóncavo (L, U, T).
(defun cross2 (a b c)
  (- (* (- (car b) (car a)) (- (cadr c) (cadr a))) (* (- (cadr b) (cadr a)) (- (car c) (car a)))))
(defun area2 (pts / n i s a b)
  (setq n (length pts) i 0 s 0.0)
  (while (< i n)
    (setq a (nth i pts) b (nth (rem (+ i 1) n) pts))
    (setq s (+ s (- (* (car a) (cadr b)) (* (car b) (cadr a)))))
    (setq i (+ i 1)))
  s)
(defun en-tri (p a b c)
  (and (>= (cross2 a b p) 0.0) (>= (cross2 b c p) 0.0) (>= (cross2 c a p) 0.0)))
(defun quitar-nth (lst k / r i)
  (setq r nil i 0)
  (foreach q lst (if (/= i k) (setq r (cons q r))) (setq i (+ i 1)))
  (reverse r))
(defun orejas (pts / v tris n i a b c ok j q hallada)
  (setq v (if (< (area2 pts) 0.0) (reverse pts) pts) tris nil)
  (while (> (length v) 3)
    (setq n (length v) i 0 hallada nil)
    (while (and (< i n) (not hallada))
      (setq a (nth (rem (+ i n -1) n) v) b (nth i v) c (nth (rem (+ i 1) n) v))
      (if (> (cross2 a b c) 0.000000001)
        (progn
          (setq ok 1 j 0)
          (while (and ok (< j n))
            (setq q (nth j v))
            (if (and (not (equal q a)) (not (equal q b)) (not (equal q c)) (en-tri q a b c)) (setq ok nil))
            (setq j (+ j 1)))
          (if ok (setq tris (cons (list a b c) tris) v (quitar-nth v i) hallada 1))))
      (setq i (+ i 1)))
    (if (not hallada) (setq v (list (car v) (cadr v) (caddr v)))))
  (if (= (length v) 3) (setq tris (cons v tris)))
  tris)
(defun solid-extrude (pts hh lay col / n i a b tris cnt)
  (setq n (length pts) i 0 cnt 0)
  (while (< i n)
    (setq a (nth i pts) b (nth (rem (+ i 1) n) pts))
    (cara a b (p+ b 0 0 hh) (p+ a 0 0 hh) lay col)
    (setq cnt (+ cnt 1) i (+ i 1)))
  (foreach tr (orejas pts)
    (cara (nth 0 tr) (nth 1 tr) (nth 2 tr) (nth 2 tr) lay col)
    (cara (p+ (nth 0 tr) 0 0 hh) (p+ (nth 1 tr) 0 0 hh) (p+ (nth 2 tr) 0 0 hh) (p+ (nth 2 tr) 0 0 hh) lay col)
    (setq cnt (+ cnt 2)))
  cnt)
;;; ---------- REVOLVE: perfil (lista de (r z)), giro alrededor del eje Z por el centro c ----------
(defun rev-pt (c rz th) (p+ c (* (car rz) (cos th)) (* (car rz) (sin th)) (cadr rz)))
(defun solid-revolve (c perfil n lay col / k i th0 th1 a b cnt)
  (setq k 0 cnt 0)
  (while (< k (- (length perfil) 1))
    (setq a (nth k perfil) b (nth (+ k 1) perfil) i 0)
    (while (< i n)
      (setq th0 (* 2 pi (/ i (float n))) th1 (* 2 pi (/ (+ i 1) (float n))))
      (cara (rev-pt c a th0) (rev-pt c a th1) (rev-pt c b th1) (rev-pt c b th0) lay col)
      (setq cnt (+ cnt 1) i (+ i 1)))
    (setq k (+ k 1)))
  cnt)
;;; ---------- SURFACE: z = f(x, y) sobre un rectángulo, coloreada por altura ----------
(defun aci (z zmax) (cond ((< z (* 0.2 zmax)) 5) ((< z (* 0.4 zmax)) 4) ((< z (* 0.6 zmax)) 3) ((< z (* 0.8 zmax)) 2) (t 1)))
(defun surf-mesh (fn c x0 x1 y0 y1 nx ny zmax lay / i j xa xb ya yb pa pb pc pd)
  (setq j 0)
  (while (< j ny)
    (setq i 0)
    (while (< i nx)
      (setq xa (+ x0 (* (- x1 x0) (/ i (float nx)))) xb (+ x0 (* (- x1 x0) (/ (+ i 1) (float nx))))
            ya (+ y0 (* (- y1 y0) (/ j (float ny)))) yb (+ y0 (* (- y1 y0) (/ (+ j 1) (float ny)))))
      (setq pa (p+ c xa ya (apply fn (list xa ya))) pb (p+ c xb ya (apply fn (list xb ya)))
            pc (p+ c xb yb (apply fn (list xb yb))) pd (p+ c xa yb (apply fn (list xa yb))))
      (cara pa pb pc pd lay (aci (/ (+ (caddr pa) (caddr pb) (caddr pc) (caddr pd)) 4.0) zmax))
      (setq i (+ i 1)))
    (setq j (+ j 1)))
  (* nx ny))
;;; ---------- la escena ----------
(defun domo (x y) (max 0.0 (* 1.4 (- 1.0 (+ (* (- x 1.0) (- x 1.0)) (* (- y 1.0) (- y 1.0)))))))
(setq nCaja (solid-box '(0.0 0.0 0.0) 2.0 1.2 1.0 "CAJA" 5))
(setq nCil  (solid-cylinder '(3.6 0.6 0.0) 0.6 1.6 24 "CILINDRO" 3))
(setq nEsf  (solid-sphere '(5.4 0.6 0.6) 0.6 24 12 "ESFERA" 1))
(setq nExt  (solid-extrude '((0.0 3.0 0.0) (2.4 3.0 0.0) (2.4 4.0 0.0) (1.0 4.0 0.0) (1.0 5.4 0.0) (0.0 5.4 0.0)) 0.35 "EXTRUSION" 2))
(setq nRev  (solid-revolve '(4.0 4.2 0.0) '((0.0 0.0) (0.6 0.0) (0.8 0.4) (0.45 0.9) (0.35 1.3) (0.55 1.7) (0.6 1.8)) 24 "REVOLUCION" 6))
(setq nSup  (surf-mesh 'domo '(5.6 3.2 0.0) 0.0 2.0 0.0 2.0 20 20 1.4 "SUPERFICIE"))
(setq nTotal (sslength (ssget "_X" '((0 . "3DFACE")))))
#fin
#: Caras dibujadas por comando: BOX **@{nCaja}**, CYLINDER **@{nCil}**, SPHERE **@{nEsf}**, EXTRUDE **@{nExt}**, REVOLVE **@{nRev}**, superficie **@{nSup}**. Leídas de vuelta del dibujo con ssget: **@{nTotal}** caras 3DFACE en total.
#: **Cómo se usa** (igual que se teclea en AutoCAD, pero como función): `(solid-box '(x y z) dx dy dz "CAPA" color)` · `(solid-cylinder centro radio altura n "CAPA" color)` · `(solid-sphere centro radio nu nv "CAPA" color)` · `(solid-extrude contorno altura "CAPA" color)` · `(solid-revolve centro perfil n "CAPA" color)` · `(surf-mesh 'f centro x0 x1 y0 y1 nx ny zmax "CAPA")`.
