;;;; Pruebas del motor numérico (engine.lisp, hn-* / hnb-*), sin la app.
;;;; sbcl --script tests/numerico/test_hn_runtime.lisp   → imprime "N/N OK" o los fallos.
(load (merge-pathnames "../../engine.lisp" *load-truename*))
(setf *read-default-float-format* 'double-float)
(defvar *ok* 0) (defvar *mal* 0)
(defun cerca (a b &optional (tol 1d-9))
  (cond ((and (numberp a) (numberp b)) (<= (abs (- a b)) (* tol (max 1 (abs a) (abs b)))))
        ((and (vectorp a) (vectorp b) (= (length a) (length b))) (every (lambda (x y) (cerca x y tol)) a b))
        (t (equalp a b))))
(defmacro prueba (nombre forma esperado &optional (tol 1d-9))
  `(let ((v (handler-case ,forma (error (c) (list :error (format nil "~a" c))))))
     (if (cerca v ,esperado ,tol) (incf *ok*)
         (progn (incf *mal*) (format t "MAL ~a: ~s  (esperado ~s)~%" ,nombre v ,esperado)))))
(defun m (&rest filas) (map 'simple-vector (lambda (f) (coerce f 'simple-vector)) filas))

;; aritmética con difusión y producto matricial
(prueba "escalar+matriz" (hn+ 1 (m '(1 2) '(3 4))) (m '(2 3) '(4 5)))
(prueba "A·v" (hn* (m '(1 2) '(3 4)) (vector 1 1)) (vector 3 7))
(prueba "v'·v = escalar" (hn* (hn-tr (vector 1 2 3)) (vector 1 2 3)) 14)
(prueba "v·w (Calcpad: producto escalar)" (hn* (vector 1 2 3) (vector 4 5 6)) 32)
(prueba "Bᵀ·D·B 16×16" (length (hn* (hn* (hn-tr (hnb-ones 3 16)) (hnb-eye 3)) (hnb-ones 3 16))) 16)
(prueba "1/3 → double" (hn/ 1 3) (/ 1d0 3))
(prueba "6/6 entero" (hn/ 6 6) 1)
(prueba "10^-4" (hn^ 10 -4) 1d-4)
(prueba "A^-1" (hn^ (m '(4 1) '(2 3)) -1) (m '(0.3 -0.1) '(-0.2 0.4)))
(prueba ".* elemento a elemento" (hn.* (vector 1 2 3) (vector 2 2 2)) (vector 2 4 6))
;; rangos, índices y asignación indexada
(prueba "rango 1:4" (hn-range 1 4) (vector 1 2 3 4))
(prueba "rango 10:-3:1" (hn-range 10 1 -3) (vector 10 7 4 1))
(prueba "A(2, 1:2)" (hn-ref (m '(1 2 3) '(4 5 6)) 2 (hn-range 1 2)) (vector 4 5))
(prueba "A(:, 3)" (hn-ref (m '(1 2 3) '(4 5 6)) :all 3) (vector 3 6))
(prueba "v([1 3])" (hn-ref (vector 10 20 30) (vector 1 3)) (vector 10 30))
(prueba "K(g, g) += k" (let ((k (hnb-zeros 3 3)) (g (vector 1 3)))
                         (hn-set k (hn+ (hn-ref k g g) (m '(1 2) '(3 4))) g g))
        (m '(1 0 2) '(0 0 0) '(3 0 4)))
(prueba "M(:, j) = v" (hn-set (hnb-zeros 3 2) (vector 7 8 9) :all 2) (m '(0 7) '(0 8) '(0 9)))
(prueba "crece como MATLAB" (hn-set 0 5 3) (vector 0 0 5))
(prueba "fuera de rango da error"
        (handler-case (hn-ref (vector 1 2) 3) (error () :error)) :error)
;; [ ]: concatenación
(prueba "[1, 2, 3]" (hn-cat (list (list 1 2 3))) (vector 1 2 3))
(prueba "[v; w] = filas" (hn-cat (list (list (vector 1 2)) (list (vector 3 4)))) (m '(1 2) '(3 4)))
(prueba "[v, w] = seguido" (hn-cat (list (list (vector 1 2) (vector 3 4)))) (vector 1 2 3 4))
;; sistemas: LU (lsolve) y Cholesky (clsolve de Calcpad)
(prueba "lsolve" (hnb-lsolve (m '(4 1) '(2 3)) (vector 1 2)) (vector 0.1 0.6))
(prueba "clsolve" (hnb-clsolve (m '(4 2 0) '(2 5 1) '(0 1 3)) (vector 2 3 4)) (hnb-lsolve (m '(4 2 0) '(2 5 1) '(0 1 3)) (vector 2 3 4)))
(prueba "clsolve no definida positiva → error"
        (handler-case (hnb-clsolve (m '(1 2) '(2 1)) (vector 1 1)) (error () :error)) :error)
(prueba "det" (hnb-det (m '(4 1) '(2 3))) 10d0)
;; integrales (Gauss-Legendre adaptativa; integrando escalar o MATRIZ)
(prueba "∫x^7 0..1" (hnb-integral (lambda (x) (expt x 7)) 0 1) 0.125d0 1d-12)
(prueba "∫sin 0..π" (hnb-integral (lambda (x) (sin x)) 0 pi) 2d0 1d-10)
(prueba "∬ x·y" (hnb-integral2 (lambda (x y) (* x y)) 0 1 0 1) 0.25d0 1d-12)
(prueba "∫ matriz" (hnb-integral (lambda (x) (m (list x (* x x)))) 0 1) (m '(0.5d0 0.3333333333333333d0)) 1d-12)
;; spline de Calcpad: pasa por los nudos y es simétrico
(prueba "spline en un nudo" (hnb-spline 2 3 (m '(0 0 0 0) '(0 1 5 0) '(0 0 0 0))) 5)
(prueba "spline 1-D en un nudo" (hnb-spline 3 (vector 1 4 9 16)) 9)
;; round de escuela (0.5 se aleja del cero), como Calcpad
(prueba "round(2.5)" (hnb-round 2.5) 3)
(prueba "round(-2.5)" (hnb-round -2.5) -3)
(prueba "round(6.6290014, 3)" (hnb-round 6.6290014 3) 6.629d0)
;; salida hacia la hoja
(prueba "literal matriz" (hn-lit (m '(1.5 2) '(3 1d20))) "(vector (vector 1.5 2) (vector 3 1e20))")
(format t "~a/~a OK~%" *ok* (+ *ok* *mal*))
(sb-ext:exit :code (if (zerop *mal*) 0 1))
